### ISSUE TITLE
No default storage location - SleekDB 0.7.1

### ISSUE THREAD

**Issue by rakibtg** [rakibtg/SleekDB#1]
SleekDB 0.7.1 saves data inside the `vendor` directory if no custom path was found inside the config file, but it seems to be confusing and a very good chance that the developer would lost all the data while doing a compose update or installation.

The solution would be simpler,
- Look for a location in the config file, where SleekDB can write data.
- If no default location was provided in the config file then raise an error.

Feel free to reply to this issue if you have a better plan.

**Comment by leealexey** [comment]
I think it'll be ok to set `sys_get_temp_dir() `as default directory, also documentation should mention that this folder will be cleaned up on next boot of the server. This is not perfect solution but at least it is better than throwing exception 😉
