### ISSUE TITLE
Foreign keys with cascade on update and or delete

### ISSUE THREAD

**Issue by Dennis4720** [rakibtg/SleekDB#100]
Hi!

Firstly, thank you for creating such an awesome project. 

I'm really interested in replacing MariaDB with SleekDB but after reading some documentation I found out that there's no such thing as foreign keys that deletes data in other tables once a value got updated/deleted. Is that correct?

If so, I'd love to see this feature in SleekDB.

Kind regards,
Dennis.

**Comment by Timu57** [comment]
SleekDB does aim to be a "document based" NoSQL databse.
In that kind of databases constraints like foreign keys normally doesn't exist.

You need to either structure your database in a way where you don't need constrains or you have to manage cascading updates and deletes by your own by executing additional queries.

That said, it could be that you have a good idea how we could realize that kind of feature. It would be nice if you could write something like a theoretical concept how we could achieve a foreign key constraint in an efficient way.

**Comment by Timu57** [comment]
I don't think that we implement constraints into this NoSQL database anytime soon.
So I will close this issue for now, feel free to reopen.
