### ISSUE TITLE
findOneBy causes Undefined array key "order" warning

### ISSUE THREAD

**Issue by peterbrinck** [rakibtg/SleekDB#101]
Hi!

When using `findOneBy` I'm getting a ```Undefined array key "order"``` warning.

Looking in the docs, it doesn't seem I'm using it wrong.
This is my criteria: `['serialNumber', '=', $deviceData->serialNumber]`

The full warning:
`Warning: Undefined array key "order" in vendor/rakibtg/sleekdb/src/Query.php on line 510`
https://github.com/rakibtg/SleekDB/blob/master/src/Query.php#L510

**Comment by Timu57** [comment]
Hi,
thank you for reporting the bug.
Does that bug still occur with v2.1.1?

### Updating with composer
```bash
composer update rakibtg/sleekdb
```

**Comment by peterbrinck** [comment]
Oh cool, didn't know there was a new release!
I'll give it a go.

**Comment by peterbrinck** [comment]
The new release (v2.1.1) works fine!

Thanks for the quick reply 👍
