### ISSUE TITLE
How I know what version I have ?

### ISSUE THREAD

**Issue by jmencoder** [rakibtg/SleekDB#102]
Sorry for the question but I took a project that have this library include but I can't find the version.

**Comment by Timu57** [comment]
Hi @jmencoder
If composer is used to manage the packages in that project just type:

```bash
composer show rakibtg/sleekdb
```

else

Please check if for example the Store class exists (introduced in v2) if not you should consider upgrading soon.

SleekDB v2 provides full backwards compatibility, it just dropped PHP 5 support and needs at least PHP 7.0.

**Comment by jmencoder** [comment]
Thnks!

The project doesn't use composer and I definitely do not have version 2, the Store class doesn't exist.

**Comment by rakibtg** [comment]
@jmencoder Please use the latest version! Closing this issue, feel free to re-open.
