### ISSUE TITLE
Typo in Getting Started guide

### ISSUE THREAD

**Issue by Largo** [rakibtg/SleekDB#103]
https://sleekdb.github.io/#/getting-started

`$article = [
 "title" => "Google Pixel XL",
 "about" => "Google announced a new Pixel!",
 "author" => [
   "avatar": "profile-12.jpg",
   "name" : "Foo Bar"
 ]
];
$results = $newsStore->insert($article);`

should be 
` "author" => [
   "avatar"=>"profile-12.jpg",
   "name" =>"Foo Bar"
 ]`

**Comment by Timu57** [comment]
Thank you for reporting the typo. It's fixed now.
