### ISSUE TITLE
Deprecate nestedWhere and implement nested where functionality into where and orWhere methods

### ISSUE THREAD

**Issue by Timu57** [rakibtg/SleekDB#112]
That would reduce the amount of methods (complexity) and the OUTERMOST_OPERATION part of the nestedWhere method.

**Comment by adrxn** [comment]
This is about what I meant.
Make only 1 where in which you can do all selections with nested and's and or's.
I think you can deprecate orwhere as well, because you can use 'or' in the nested version.

Perhaps something should be invented for NOT.


I don't know if you have any experience with LINQ in .NET ? 
LINQ where function can contain almost all you want in selections.

**Comment by adrxn** [comment]
Watch this:
https://stackoverflow.com/questions/5792388/is-there-something-in-php-equivalent-to-linq-in-c
https://github.com/Athari/YaLinqo

**Comment by adrxn** [comment]
Some examples of the array syntax that should be possible IMO:

.where {
		[
			[[ "name", "like", "a*" ], "or", [ "name", "like", "b*" ]], 
			"and", 
			[
				[[ "age", ">=", 15 ], "and", [ "age", "<", 30 ], "and", [ "haschildren", "=", true ]],
				"or", 
				[[ "age", ">=", 45 ], "and", [ "age", "<", 60 ]]
			],
			"and",
			[ "city", "=", "New York" ]
		]
);

.where([ "city", "=", "Los Angeles" ]);

.where([[ "age", "=", 20 ], "or", [ "age", "=", 24 ], "or", [ "age", "=", 28 ], "or", [ "age", "=", 32 ]]);


- More than 1 "and" and/or "or" in 1 array.
- If one array contains mixed "and" and "or", precedence rules have to be taken into account.
- Nested arrays are needed to force precedence, similar to brackets in sql-like expressions.


The most beautiful thing would be if you can manage to implement full LINQ functionality for SleekDB.
Then you are able to join, order, groupby, take, skip etc.
But that is quite a job ... :)

**Comment by Timu57** [comment]
> Make only 1 where in which you can do all selections with nested and's and or's.
> I think you can deprecate orwhere as well, because you can use 'or' in the nested version.

Hi @adrxn Thank you for your comments.
I think we shouldn't deprecate/ remove the `orWhere` method, because I think it is more intuitive and much easier for new users and use cases where the statement is very simple.
What do you think regarding that topic @rakibtg ? Should we keep or remove it? At the end it's just a design choice and nothing big..

>     * More than 1 "and" and/or "or" in 1 array.
> 
>     * If one array contains mixed "and" and "or", precedence rules have to be taken into account.
> 
>     * Nested arrays are needed to force precedence, similar to brackets in sql-like expressions.

The PR #113 adds all the things you want :+1: 

> The most beautiful thing would be if you can manage to implement full LINQ functionality for SleekDB.
> Then you are able to join, order, groupby, take, skip etc.
> But that is quite a job ... :)

I looked a little bit into LINQ and it looks really interesting. I think SleekDB will stick with an implementation that provides the user a more SQL-Like interface to work with. SQL is known by almost everybody working in the tech industry and learning it is very easy.
`join`, `orderBy`, `skip` etc. already exist and with the time more and more functionality will come.
The most important things are already implemented and hopefully SleekDB will cover every functionality soon.
PRs are always welcome :blush:

**Comment by rakibtg** [comment]
> What do you think regarding that topic @rakibtg ? Should we keep or remove it? At the end it's just a design choice and nothing big..

@Timu57 Let's keep them.

**Comment by Timu57** [comment]
Implemented with version 2.3.
