### ISSUE TITLE
How do I make a query "SELECT BETWEEN"

### ISSUE THREAD

**Issue by jmencoder** [rakibtg/SleekDB#121]
Could you write me an example to do a query "BETWEEN" with dates yyyy/mm/dd.
Thnks!

**Comment by Timu57** [comment]
Hi @jmencoder 
You can achieve that functionality very easy:

```php
<?php

require_once './vendor/autoload.php';

use SleekDB\Store;

// create store
$databaseDirectory = __DIR__ . "/database";
$newsStore = new Store("news", $databaseDirectory);

// Convert the date-strings to timestamps
$date = new \DateTime("2020/12/01");
$startDate = $date->getTimestamp();

$date = new \DateTime("2021/01/04");
$endDate = $date->getTimestamp();

// Alternative conversion in one line:
$startDate = (new \DateTime("2020/12/01"))->getTimestamp();
$endDate = (new \DateTime("2021/01/04"))->getTimestamp();

// Get result
// WHERE releaseDate >= $startDate AND releaseDate <= $endDate
$news = $newsStore->findBy([ ["releaseDate", ">=", $startDate], ["releaseDate", "<=", $endDate] ]);

// print result
var_dump($news);

```

As you can see when using PHPs DateTime class it is very easy. https://www.php.net/manual/en/class.datetime.php

You should also save the date you want to check as a timestamp.

When you need to convert it back to an string just use the following:

```php
$releaseDate = (new DateTime($timestamp))->format("'Y/m/d");
```

**Comment by Timu57** [comment]
@jmencoder with the new version 2.5 we added support for DateTime objects and the two new conditions `BETWEEN` and `NOT BETWEEN`.

Visit our new ["Working with Dates" documentation](https://sleekdb.github.io/#/dates) for more details on how to handle dates.

Feel free to reopen this issue if you have further questions.
