### ISSUE TITLE
Dont Delete this Function!

### ISSUE THREAD

**Issue by gusgeek** [rakibtg/SleekDB#125]
Hi there! It is always a pleasure to talk about this project, it is incredible.

I would like to know, if there is the possibility of keeping the function ''' where()->update ''' as a quick and practical option to an Update.

**Comment by Timu57** [comment]
Hi @gusgeek 

Do you mean without the `getQuery` in between the `where` and `update` methods?

```php
where()->update();
// instead of
where()->getQuery()->update();
```

**Comment by gusgeek** [comment]
Exactly, I think the more minimalist the functions are, the easier and more practical the programming mode will be. From version to version several functions changed and this in wanting to update the Framework ends up being a headache, so you have to rewrite one or more of the code. 
An example is the cool function `findById` replacing `where ('user', '=', 1)-> fetch ()`

**Comment by gusgeek** [comment]
It occurs to me that it could be something like 

```
$blogPost->updateById($array);
```

Retrieving the specificity of the search in a line

**Comment by Timu57** [comment]
I am sorry but I don't quite understand what exactly you mean now..
Do you suggest we should implement a new function called `updateById` or do you want that we try to remove the `getQuery` between the `where` and `update`?

PS: We already have the method `update` in the Store class: [Edit Data documentation](https://sleekdb.github.io/#/edit-data)

**Comment by gusgeek** [comment]
I apologize, I am doing many things at the same time.

I find that SleekDB is up to date, I decide to update a project to the latest version and they have made changes at the function level that in this step are a headache since they have to be rewritten.

My main comment was: It would be nice to leave the function as it was in 2.1 if I am not mistaken, as it is simple, easy to memorize and practice programming.

```
$blogCategories->where('_id', '=', 1)->update (["title" => $ _POST ['title']]);
```

On the other hand, I bring the idea that it would be good if they are going to change this, make it minimalist, an example is the `findById(id)` function, it would be good, if there is one that is `updateById (id, array)`.

**Comment by Timu57** [comment]
Ah ok, I understand your point now.

We are really sorry that upgrading from version 1.5 to 2.X is such a pain.

Before version 2.0 SleekDB had a completely different codebase.
It was a single class using multiple traits.
That had many flaws regarding maintainability, extensibility and usability.
A little bit more on that is explained in #84.

We refactored and rewrote the whole project with separation of concerns and the future of SleekDB in mind.

Such a big change will not happen again!
Now the codebase of SleekDB is in a state where it can evolve and don't need drastic changes ever again.

You have plenty of time to upgrade your codebase to the new Store, QueryBuilder and Query classes.
At the moment we have no plans of releasing the next major version (3.0) anytime soon.

The `updateById(id, array)` is a really good idea!
It is not difficult to implement and I could do that within the next days.
Could you please open a new issue for that? :relaxed:  Thank you.

**Comment by gusgeek** [comment]
Of course! I understand the generational change, well, it was a rather constructive criticism. The product is excellent and it has me in love!
Thanks for your attention! I will initiate the Issue for which I proposed.
