### ISSUE TITLE
I present an idea: updateById 

### ISSUE THREAD

**Issue by gusgeek** [rakibtg/SleekDB#126]
Seeing the great work they are doing, I got to know the findById (id) function which optimizes my work a lot. Taking this idea, it would be great if they did the same with the Update argument something like updateById (id, array).

An example would be:
```
$array = array(
	'loginDate' => date('Y-m');
);

$blogUsers->updateById($_GET['id'], $array);
```

In conclusion, it would be amazing to be able to concentrate an update in a short and fast function.

**Comment by Timu57** [comment]
Implemented with version 2.6
