### ISSUE TITLE
Unsafe Comparisons

### ISSUE THREAD

**Issue by gusgeek** [rakibtg/SleekDB#143]
I tell you that I was experimenting with the latest version of SleekDB, (**By the way, Thanks for integrating updateById**), I found that I was having problems when searching for ID in fetchById / findOneBy when I pass a String instead of Int when pointing to _id .

Will you be comparing correctly?

I was able to fix it by converting the string to int with the intval () function.

**Comment by Timu57** [comment]
Added with version 2.7.
