### ISSUE TITLE
Can't use SleekDB without Composer

### ISSUE THREAD

**Issue by dvygolov** [rakibtg/SleekDB#153]
I get "can't find IoHelper" each time I try to use SleekDb without Composer. Managed to fix it by replacing line 19 in Store.php to
`foreach (glob(__DIR__ . '/Classes/*.php') as $traits) {`

Also had to add these lines to Query.php:
```
require_once __DIR__.'/Classes/CacheHandler.php';
require_once __DIR__.'/Classes/DocumentFinder.php';
require_once __DIR__.'/Classes/DocumentUpdater.php';
```

**Comment by Timu57** [comment]
Thank you for reporting the bug.

Fixed with version 2.7.2.

PS: When using SleekDB without composer just use the following line:
```php
require_once __DIR__ . "<PATH_TO_SLEEKDB>/Store.php";
```
Then you can use every class.
```php

require_once __DIR__ . "<PATH_TO_SLEEKDB>/Store.php";

use SleekDB\Store;
use SleekDB\Query;

// ...
```
