### ISSUE TITLE
Should we replace all mentions of "_id" in the documentation

### ISSUE THREAD

**Issue by Timu57** [rakibtg/SleekDB#165]
SleekDB allows users to define their own primary key, for example "id" or "pk" instead of using the default "_id" key.

Should we replace all mentions of "_id" with "primary key"?

### Example 1

Current:
Returns the inserted document as an array including the automatically generated and unique _id property.

After:
Returns the inserted document as an array including the automatically generated and unique primary key property.

### Example 2

Current:
This method is especially fast because it uses the _id to update the document directly instead of traversing through all documents.

After:
This method is especially fast because it uses the primary key to update the document directly instead of traversing through all documents.

**Comment by rakibtg** [comment]
@Timu57 If we keep `_id` by default then let's keep it there. Some where in the doc we need to explain this issue as well.

**Comment by Timu57** [comment]
You are right, we should let it as is. If someone changes the _id primary key they know what they have done and should understand the _id mentions correctly.
