### ISSUE TITLE
Selecting a document with array key

### ISSUE THREAD

**Issue by yssunjoko** [rakibtg/SleekDB#174]
I've got a document containing:
"category":["a", "b", "c"]

and this is how I try to fetch the document:

$params = [];
array_push($params, ["category", 'in', "a"]);
$docs = $collection->findBy($params);

and it doesn't work.
I believe there should be some ways to fetch it, in case the data is labelled by some multiple categories.
Can you help?

**Comment by Timu57** [comment]
Hi @yssunjoko the feature you ask for is currently not implemented.

The `IN` condition checks if the value of a field ("category") is in a given data array.

We could provide that feature by implementing `CONTAINS` and `NOT CONTAINS` as new conditions.

That new conditions could do two things:

1. If the field value is an array it checks if the data is (not) found in that array. (Check against first array level)
2. If the field value is a string it checks if the string contains the given data. (data has to be a string too)

**Comment by Timu57** [comment]
I would like to hear your opinions.
With the next release we will introduce two new conditions `CONTAINS` and `NOT CONTAINS`.

They check if an attribute of a stored document contains or not contains a given value.

For example an article that has a `tags array`.

### CONTAINS

It will return `true` if tags is an array and the array contains "value".

### NOT CONTAINS

Two possible solutions:

1. It returns `true` if tags is an array and the array does not contain "value".
2. It returns `true` if tags is not an array (for example `null`) or the array does not contain "value".

### Question

The question I have is how to implement `NOT CONTAINS`

What do you think is the better Solution?
**Solution 1** or **Solution 2**?

Thanks to all of you in advance :relaxed:

**Comment by Timu57** [comment]
Implemented with version 2.9

**Comment by yssunjoko** [comment]
Hello @Timu57 I'm so sorry for so being so late replying.
Thanks for implementing the CONTAINS and NOT CONTAINS.
I think I prefer Solution 2 to the other.
