### ISSUE TITLE
Insert at position?

### ISSUE THREAD

**Issue by rajeshsharmadl** [rakibtg/SleekDB#175]
Is there any way to insert record at a particular position of collection?

**Comment by Timu57** [comment]
Hi @rajeshsharmadl 
I don't quite understand what you mean, could you please explain your use case?

**Comment by rajeshsharmadl** [comment]
I am developing a website where I may need to insert record into existing collection but at a particular position. This way, when data loads, the entry loaded in last, will still be displayed at the selected position.

I hope, I am able to clarify.

**Comment by Timu57** [comment]
@rajeshsharmadl I think I get what you mean.

If you want to return the documents always in a specific order you can do that by your own.
SleekDB provides everything you need to make that kind of functionality.

Example solution:

For every document you save a attribute called "position".
The first document will have the position = 1, the second one position = 2 and so on..

If you have for example 20 documents and you want to insert a new document and it should have the position = 2 you give it the position = 2 and increment  the positions of all documents saved with position >= 2 with 1.

When retrieving all documents you now just need to order by position in a ascending order.

Hope I could help.
If you have any further questions don't hesitate to ask.

**Comment by rajeshsharmadl** [comment]
Thanks.

This is an excellent solution and should work fine. I will give it a try.

Regards

**Comment by Timu57** [comment]
Nice to hear that I could help you.
I will close the issue for now, feel free to reopen it if needed.
