### ISSUE TITLE
Several files for each new data in a store

### ISSUE THREAD

**Issue by zeustakes** [rakibtg/SleekDB#176]
Hi, I tried SleekDB, and it looks great, but I have a question about it, when I insert data, I can see in the file structure of the "store" (/data) one .json file per each register, that's  how it works?, may not be better to fill all in one single .json (that is /cache), don't understand how it can be fast with all these files, for example for 20000 registers I will have 20000 files, I think this will be slow to process, can you explain more about how it works? Thanks.

![image](https://user-images.githubusercontent.com/81091940/111907420-34d82100-8a23-11eb-9f75-e18f374c20cc.png)

**Comment by Timu57** [comment]
Hi @zeustakes 
Thank you for your interest and questions.

> Hi, I tried SleekDB, and it looks great, but I have a question about it, when I insert data, I can see in the file structure of the "store" (/data) one .json file per each register, that's how it works?

Yes, that is how SleekDB currently works.

> may not be better to fill all in one single .json (that is /cache)

That is discussed in #26 and #140.
We could not figure out how to create an efficient solution with a single file.
The first thing we want to avoid is to load all documents into the memory every time.
That problem could be solved somehow but the main problem is updating/ deleting documents.
If you have a big file and you want to delete or update a document (line) you need to rewrite the whole document.
That is slow for big files.
One solution we can think of is to let a worker handle all updates and deletes but it is currently not possible to create a reliable worker with PHP 7, so external tools like supervisor are needed to keep the worker alive.
We hope future releases of PHP will make it possible to create reliable workers.
PS: If you have an idea for a solution or want to contribute, please let us know, we appreciate every type of help!

> don't understand how it can be fast with all these files, for example for 20000 registers I will have 20000 files, I think this will be slow to process, can you explain more about how it works?

SleekDB uses a Result-Cache.
I will try to explain it with an example:

```php
<?php

use SleekDB\Store;

$userStore = new Store("users", __DIR__ . "/data");

// Get all admins query
$result = $userStore->findBy(["role", "=", "admin"]);
```

First time the "Get all admins query" is executed SleekDB traverses through all documents, returns the result and saves the result in a cache file.
On all following calls to the same query (`role = "admin"`) SleekDB just returns the result saved in the Cache, so it does not traverse through all documents again.

On default Cache-Files doesn't have a cache lifetime. (Can be configured [Store wide](https://sleekdb.github.io/#/configurations#cache_lifetime) or on a [query by query base](https://sleekdb.github.io/#/cache-management))
PS: A cache lifetime is not needed/ recommended in most use cases.

Cache files without a lifetime will be deleted on every insert/ update/ delete.

Hope I could clarify some things. If you need more explanation or help don't hesitate to ask.

**Comment by Timu57** [comment]
Hope I was able to clarify some things and help you a little bit.
I will close this issue for now, please feel free to reopen it if needed.
