### ISSUE TITLE
Unique insert

### ISSUE THREAD

**Issue by daussho** [rakibtg/SleekDB#177]
Can we implement unique insert, so it will search for duplicate key/value in document, and if it not exist, it will insert the document or it will throw error.

**Comment by Timu57** [comment]
Hi @daussho 
Thank you for you feature request and great idea.
@rakibtg would like to hear you opinion on my following thoughts too.

Currently SleekDB is a completely schema less document database.

The implementation of a functionality to only insert something if no document with a specific value in a specific field exist is quite easy.

```php
<?php
use SleekDB\Store;

$userStore = new Store("users", __DIR__ . "/database");

$newUser = [
  "email" => "info@sleekdb.com",
  "forename" => "Tim",
  // ...
];

$emailExists = $userStore
  ->createQueryBuilder()
  ->where(["email", "=", $newUser["email"]], "OR", ["forename", "=", $newUser["forename"]])
  ->getQuery()
  ->exists();

if($emailExists === false){
  $userStore->insert($newUser);
}
```

But a "unique" feature could be interesting if the user needs to make many fields unique.
But if we decide to implement it we should not just implement a method "unique" or something.

I would say then we should plan to implement something like a "Schema-Feature" where the user can define a schema for a store.

That schema could include many conditions to validate new documents before inserting them:

- required
- unique
- int
- float
- min
- minLength
- maxLength
- array
- string
- email
- numeric
- AND MUCH MORE...

**Comment by daussho** [comment]
I think it is good idea to implement db schema to make db rule more easy to understand, for now I'm usually use [array validation](https://github.com/rakit/validation) for enforcing schema to my database. But array validation not working with validation that need data from db, hence I'm thinking adding this feature.

**Comment by Timu57** [comment]
That looks interesting:
https://github.com/laravel/framework/tree/8.x/src/Illuminate/Validation

**Comment by daussho** [comment]
> That looks interesting:
> https://github.com/laravel/framework/tree/8.x/src/Illuminate/Validation
> 
> Documentation:
> https://laravel.com/docs/8.x/validation

Can this library use without laravel? 
The library i linked above can be used as a standalone, and actually it can used custom validation like unique and check db to verifiy if data is unique.

And now I'm thinking if this feature implemented, we should also implemented database transaction. Say if I insert many data, and one of my data not valid based on the schema, it will throw error and the insert operation stop. If this is happens, I want to revert the database to previous state.

**Comment by Timu57** [comment]
It seems like the `rakit/validation` has a very similar implementation like `Illuminate\Validation`.

We try to avoid dependencies, and we probably need to make optimize the validation process for our needs.
But both implementations are very easy to understand and MIT licensed. So we probably can borrow some ideas they implemented.

I would like to hear what @rakibtg thinks regarding this topic.
Should we just add `rakit/validation` as a dependency and expand it to make features like unique possible or should we implement a validation feature inspired by both repos, mentioned above, ourself?

**Comment by Timu57** [comment]
I separated this issue into two independent issues.
I will close this issue, feel free to reopen it if needed.
