### ISSUE TITLE
Implement predicate-based filters

### ISSUE THREAD

**Issue by ooa113y** [rakibtg/SleekDB#18]
This would allow to implement any custom filter the user desires alongside with the existing simple filters of `where`, `orWhere`, `in`, etc. Example code would look like:
```php
$db
    ->filter(
        'column', 
        function ($value) { return $value == 0; }
    )->fetch();
```

**Comment by rakibtg** [comment]
@ooa113y That's an excellent idea! Do you have any solution in mind?

**Comment by ooa113y** [comment]
Ah, sorry, I have unfortunately not even looked at the actual code of SleekDB, so I have no idea how to go about implementing this myself.
