### ISSUE TITLE
Memory File DB?

### ISSUE THREAD

**Issue by arunnabraham** [rakibtg/SleekDB#191]
Since the concept is good. Is there any way this could be using `php://memory` ?

**Comment by Timu57** [comment]
Hi @arunnabraham I don't understand your question.
Would be nice if you could describe your question a little bit better.
Thank you in advance.

**Comment by Timu57** [comment]
I will close this issue for now. Please feel free to reopen it if needed.

**Comment by arunnabraham** [comment]
Hi. If I am not wrong, SleekDB uses JSON file-based database right? Hope it uses PHP array manipulation in the background.
Since it also uses `fopen` in the background, could we possibly use php://memory instead of file name?

My thought is to use it along with multiple Sharded DB environments. So I don't want to use joins directly on my RDB but fetching multiple tables which are on different DB instances and pass it to SleekDB for further manipulation. Since I don't like to use JSON file inside the server disk, could we possibly use PHP's memory file option on the existing SleekDB configuration, so effectively
improve the I/O and computation also reduce RDBMS load thereby.

example code reference: https://github.com/nanderoo/php-memory-demo/blob/master/example-01.php

**Comment by Timu57** [comment]
Do I understand it correctly? You want to save all documents/entries in the RAM? What happens if the Server goes down and the RAM is cleared?

**Comment by arunnabraham** [comment]
The memory is used only for computation which would be a temporary one.
