### ISSUE TITLE
why is there 120 second timeout and we need an option to disable timeout

### ISSUE THREAD

**Issue by bioshock** [rakibtg/SleekDB#194]
not sure why set a default 120seconds timeout ? 

should have an option to disable setting timeout for cli scripts

**Comment by Timu57** [comment]
Hi @bioshock you can set the time limit to infinite by providing zero https://www.php.net/manual/en/function.set-time-limit.php

**Comment by bioshock** [comment]
i know how to disable timeout . but setting timeout globally is not the best option.

what is reasoning behind adding timeout using set_time_limit ?
