### ISSUE TITLE
User access - Auth stuffs

### ISSUE THREAD

**Issue by thipages** [rakibtg/SleekDB#195]
Hi,
is there plan for user authentification/authorization in SleekDB roadmap  (eg through a dedicated store) ?
Thank you

**Comment by Timu57** [comment]
Hi @thipages currently there are no such plans. What could the use case for an authentication/ authorization feature be?

**Comment by thipages** [comment]
Hi,
the use case is to allow users (to log and) to change their own datasets while sharing some common datasets. In addition, this is for using within javascript.

I am not sure this is in direct SleekDB scope but it may be managed as an add-on through dedicated store/process.

This feature has been raised briefly [here ](https://github.com/rakibtg/SleekDB/issues/29#issue-568137289).

Thank you for your quick answer.
