### ISSUE TITLE
_id is converted to string

### ISSUE THREAD

**Issue by webghostx** [rakibtg/SleekDB#198]
Hi

I've been looking for a bug in my script for a long time. I noticed that "_id" suddenly became a string.

`'_id' => string '3' (length = 1)`

`$store->updateById( 3, ["_ id" => 3] );` throws an error. Nothing can happen there. But the following, of course completely nonsensical, code converts the "_id" to a string

```php
$store->createQueryBuilder()
   ->where(["$name", "=", "someone"])
   ->getQuery()
   ->update(["_id" => 3]);
```
It seems that you can only go back manually or delete the data record

regards

**Comment by Timu57** [comment]
Thank you very much for reporting that bug.
It should be fixed with SleekDB version 2.10.2.
Feel free to reopen this issue if the bug is not fixed.
