### ISSUE TITLE
Setting timeout is NOT a responsibility of this package

### ISSUE THREAD

**Issue by enumag** [rakibtg/SleekDB#205]
Found out that my console commands were failing after 2 minutes on php timeout which was nonsense because I don't use any timeout, I even have `set_timeout_limit(0)` in my `bin/console`. After investigation the culprit is your package:
https://github.com/rakibtg/SleekDB/blob/e902006b36e35f6125c936b07bd108c7d60f15d5/src/Store.php#L43
https://github.com/rakibtg/SleekDB/blob/e902006b36e35f6125c936b07bd108c7d60f15d5/src/Store.php#L744

This doesn't make any sense. Why would a package like this set a global php timeout? Let alone by default? Please get rid of this.

**Comment by Timu57** [comment]
Hi @enumag 
Thank you for your report and your suggestion.

I think that functionality was added because SleekDB can be time expensive on some circumstances, so the user can change the timeout in a convenient way with a configuration.

Your suggestion to deprecate and later remove that configuration could be a good idea.
@rakibtg what do you think about that?

PS: You can easily disable the usage of set_time_limit() by setting the `timeout` configuration to `false`. 
https://sleekdb.github.io/#/configurations#timeout

**Comment by enumag** [comment]
I'm aware ofc I did that immediately. The point is that this was completely unexpected side-effect of a library my colleague added and it caught the whole team off guard. Plus it took quite a bit of time to debug which damned library was doing such thing. Look if it makes sense for you to have this feature (I respectfully disagree) then keep it but for gods sake don't have it enabled by default.

**Comment by enumag** [comment]
In my opinion calling set_time_limit in application code is convenient enough for your users in case they need it. Having timeout configuration in a library makes sense if it's a timeout for the internal operations of that library. It shouldn't have a global side-effect like this on the entire application. Don't forget that most of the time SleekDB will be simply a service in DI container and as such will only be initialized if necessary. So some random requests would get time limit based on whether or not the library was called.

**Comment by Timu57** [comment]
I am completely on your side regarding that topic. I also don't quite understand why such a configuration was added in the first place..
The only reason why I don't remove that configuration instantly, is to ensure backwards compatibility.

If I were a part of the SleekDB community for a longer time, I possibly would've prevented the addition of that configuration.

And you are completely right. I don't know what @rakibtg says regarding that topic, but I think there is no valid and good argument for keeping that configuration. We should and will deprecate that configuration and remove it with the next major release.

**Comment by Timu57** [comment]
@enumag thank you for your input.

`timeout` is now deprecated and the whole configuration option will be removed with the next major update.
