### ISSUE TITLE
Problem with init database

### ISSUE THREAD

**Issue by geekalaa** [rakibtg/SleekDB#206]
while init the store
new \SleekDB\Store("galleries", $this->databaseDirectory);
 i am facing this error : Fatal error: Uncaught Error: Class 'SleekDB\Query' 

Php version 7.3
ubuntu
vps
nginx

**Comment by Timu57** [comment]
Hi @geekalaa 
I would like to help you, could you please provide a little bit more information?
For example:
1. What is the exact error code?
2. What did you want to do when facing that error
3. Do you have an idea yourself, why that error could have occurred?

Thank you in advance

**Comment by Timu57** [comment]
I am closing this issue due to no response.
Feel free to reopen it if you still have that issue.
