### ISSUE TITLE
UUID or non incremental _ID

### ISSUE THREAD

**Issue by bespired** [rakibtg/SleekDB#207]
Hi.
Is it possible to use a UUID or non incremental ID in sleek DB?

I’m asking for a friend.

No. It’s for me.
What I’m looking into is a DB that I can merge in Git with others using the same checkout.
I know everything is in the cloud these days, but let’s face it, that’s a security risk and a maintenance job.

What I would like is a DB that can be altered locally but will merge with no trouble with other altered DB’s 
I’m thinking a file based DB is the way to go, but that ID’s should be unique per checkout. 
This could be machine based, or UUID (hate them: unreadable to humans) or maybe git-checkout or any other configurable .env prefix.

What you guys think?
- Nah, bad idea.
- Is already made, read the manual.
- Other…
- Good, you may start right on it.

**Comment by bespired** [comment]
https://github.com/bespired/sleekdb
Created a fork to test and try it out.

Seems to work for now with:
```
<?php

$databaseFolder = realpath(__DIR__ . "/../../database");

$composerFile = realpath(__DIR__ . "/../../composer.lock");
$machineId    = base_convert(filemtime($composerFile), 10, 36);

$sleekConfig = [
    "auto_cache"     => false,
    "cache_lifetime" => null,
    "timeout"        => 120,
    "primary_key"    => '_uuid',
    "prefix_key"     => $machineId,
    "search"         => [
        "min_length" => 2,
        "mode"       => "or",
        "score_key"  => "scoreKey",
        "algorithm"  => \SleekDB\Query::SEARCH_ALGORITHM["hits"],
    ],
];
```

I don't think I can run the tests as they seem to depend on key being _id.
Will try some more and figure out how to create a pull request.

**Comment by Timu57** [comment]
Hi @bespired 
Sounds like a great idea to make the primary key more versatile.
Feel free to implement it if you want to :relaxed: 

Don't forget that it has to be implemented in a backwards-compatible way, means the **primary key** needs to be an `integer` and `_id` by **default**.

If you need any type of help or have questions, don't hesitate to ask.

PS: Asking questions and staying in contact is much easier with our [Discord Server](https://discord.gg/WJGqUFPtZw).

**Comment by bespired** [comment]
> Don't forget that it has to be implemented in a backwards-compatible way, 
> means the primary key needs to be an integer and _id by default.

Thanks for the quick response.

I see...
Well that rules out the UUID unless maybe stored as a bigInt.
The first thing I did was removing the `:int` from `increaseCounterAndGetNextId()` because 
I want to write files with a prefix to disk. It still uses the number part though to make sure the id is unique.
But yeah... `_cnt.sdb` now holds a "weird" index.  

So I guess I made my adaptations useless for this project.
Maybe I'll figure out something. After I understand the workings of the code better.
The querybuilder also looks great.

**Comment by Timu57** [comment]
The reason is very simple:

`checkAndStripId` is used in for example `findById`. Many users requested, that they want to use `findById` like this:
```php
$store->findById($_GET['id']);
```
So I changed the implementation, that these methods accept strings.
But when allowing strings, there is a big risk. 
`$_GET['id']` could contain something like these examples: 
```php
"/var/www/" // absolute path
"../../web/" // relative path
```

So I added `IoHelper::secureStringForFileAccess($id);` to secure the strings. And since the current implementation just uses numbers (int) as id / filename, there was no possibility to have a file called `11.1.json` or `1.11.json`. But I think we can change the implementation, that `secureStringForFileAccess` removed ".." instead of just ".".

**Comment by bespired** [comment]
` But I think we can change the implementation, that secureStringForFileAccess removes .. instead of ..`
Not needed for me, I was just wondering why it is there...
If you maybe already had some sort of sharding or prefixing.
I guess a uuid of ` 255-231-001`  can be changed into integer 255231001... By removing the -  
But the auto-incremental would be needed to change to a "real" uuid.
I'm not sure php would like such bigInts.

I now made that I can prefix the file with any prefix.
So the filename is now  `joeri-1.json` and if my college adds a file in his checkout of the repo it will be `name-2.json`.
The (uu)ids in the file are `joeri-1` and `name-1` etc. So not an integer, but can be incremented behind the -. 
When these repo's are merged in git they will not collide.
I'm not sure this will work for deleting records. Or when I start changing `name` records... 


And I'm not sure this is smart at all. 
The advantage to me is that I don't need to be online to add and read from this DB.
But that I do get changes other people added to the DB ( after a checkout ).
I'm using it to store developers notes on development with the code. Or that's what I'm planning on doing.

Thank you for your answers and hard work.
I'll close the issue...
