### ISSUE TITLE
Hello, is there a better ways than escape dot to address nested fields?

### ISSUE THREAD

**Issue by MerryPanda** [rakibtg/SleekDB#210]
`$userStore->updateById(24, [ "address.street" => "first street" ]);`

Dot is used as a functional symbol. So if i need to get a value that contains a dot, is escaping the only way to go or are there any more elegant solutions?

Thanks :)

**Comment by Timu57** [comment]
Hi @MerryPanda 
Can you please share a little bit more information?
A little example document perhaps would be nice and what you want/ try to do with it in detail.
I am sure we can solve your problem.

**Comment by Timu57** [comment]
I am closing this issue due to the lack of information.
Feel free to reopen it if needed.
