### ISSUE TITLE
Table Configuration and improved caching

### ISSUE THREAD

**Issue by prashant-saxena** [rakibtg/SleekDB#211]
Hi,

SleekDB is probably the best file based database solution I have found so far. Keep it up guys.
I'm getting introduced with sleekDB and I think these two features would increase the usability and performance factor.

**Table Configuration** 
When creating a store
```php
$newsStore = new \SleekDB\Store("news", $databaseDirectory, $configuration);
```
It would be better to specify field types as we do in SQL databases. For e.g.
```php
$tableConfig= [
 "title" => \SleekDB\Varchar(30, '', '/^\/([a-z]{2})\//'), // Length, default value and regex validation
 "about" => \SleekDB\Varchar(30, ''),
 "date" => \SleekDB\Datetime(mindate, maxdate, format),
"price" => \SleekDB\Float(0.0, 0.0, 10000.0, 5) // Default value, min, max and precision
"_id" => \SleekDB\Int(0)
];
```
This config should be saved on the disk. When user is executing CRUD operations on store the data should be validated against
the table config. This would prevent data corruption and provide safe guarding. Another advantage is that you don't have to save the data in key-value pair in json file. This would reduce the size of data in each row. For e.g.
```json
["Google Pixel XL","Google announced a new Pixel!","06,05,2021",5.2365, 2]
```
**Caching**
Exploring the possibilities of using external caching tools like Memcached, APC, Redis etc.
Although there is no straight forward solution to improve the caching by storing the data in memory but a careful implementation would defiantly increase the performance.

Cheers

**Comment by Timu57** [comment]
Hi @prashant-saxena 
Thank you for your kind words and ideas/ suggestions.
We already consider implementing an optional "schema" feature #189 
Your idea, that we don't have to store the keys is a nice addition :+1: thank you

The current caching-layer-implementation's main purpose was to decrease the amount of file reads after the first query.
You are completely right, detaching the caching-layer and adding it as a "plug in" could benefit the performance.

**Comment by Timu57** [comment]
@prashant-saxena I added your suggestion to #189.
I am closing this issue. Feel free to reopen it if needed.
