### ISSUE TITLE
Update on exists functionality

### ISSUE THREAD

**Issue by REDAL** [rakibtg/SleekDB#217]
Hi SleekDB,

How about the update on existing functionality?

kind regards

@rakibtg @Timu57

**Comment by Timu57** [comment]
Hi @REDAL 
Can you please specify which functionality you mean?

**Comment by REDAL** [comment]
I am referring to the "Insert into a MySQL table or update if exists" functionality

where the user makes an insert, and when adding an update if exists parameter, the system checks before insert if exists, if so, it makes an update, rather than raising an error.

check this MySQL query

INSERT INTO table (id, name, age) VALUES(1, "A", 19) ON DUPLICATE KEY UPDATE    
name="A", age=19

**Comment by REDAL** [comment]
it's the inverse of SleekDB updateOrInsert()

user insert, if the record exists, the library update the record

**Comment by Timu57** [comment]
@REDAL 
If I understand you correctly, the method `updateOrInsert()` does exactly what you want.

If an document does not exist, it will be created/inserted. If it exist, it will be updated.

**Comment by REDAL** [comment]
@Timu57 
I am talking of the inverse of update or insert

insert the record, if it does exist, update it, like the MySQL query referred to above

**Comment by Timu57** [comment]
@REDAL 
Yes, insert the document (if it does not exist).
If it exist, update it.

I think the opposite of that wouldn't make sense, would it?

**Comment by REDAL** [comment]
actually, it does, otherwise, Mysql will not add it ;),

but, I'll tell why I use it, basically to bypass try-catch statements when the record does exist, or not to check if the record does exist before updating it.

it's the same use case of updateorinsert, simply the inverse operation,

**Comment by Timu57** [comment]
@REDAL 

So you mean you want to do the following case?

If the document exists, insert it.
If the document does not exist, update it.

I think your SQL-Statement doesn't do that?

As I see it your SQL-Statement does the following:

Insert the document.
BUT if it exists, update it.

And that is exactly what `updateOrInsert()` does.

Please correct me if I'm wrong.

**Comment by REDAL** [comment]
@Timu57 

For the Mysql Query, Actually, it does insert the record, and if it exists it update it :

INSERT INTO table (id, name, age) VALUES(1, "A", 19) ON DUPLICATE KEY UPDATE
name="A", age=19

for SleekDB query command updateOrInsert(), please forgive my ignorance, I thought, that it does only update if not existing create it, in this order, I translated the sequence literally like the command name is, didn't knew it does the both verse-versa

:) 
kind regards bro

**Comment by Timu57** [comment]
@REDAL 

Don't sweat it, nothing to forgive. 
Please feel free ask anything if you have questions.
I'm glad I was able to clarify it for you :blush: 

It's the same to write:
Insert the document if it does not exist or update it, if it does exist.
OR
Update the document if it does exist or insert it, if it does not exist.

The opposite case, to update something that does not exist or insert it, if it does exist wouldn't make sense :blush:

I'm closing this issue, feel free to reopen it, if needed.
