### ISSUE TITLE
Multiple where() condition doesn't work

### ISSUE THREAD

**Issue by snoopy4ever** [rakibtg/SleekDB#22]
Hello there,

I have a problem with multiple where() conditions for my DB, I have start and end dates for my news article, I'm trying to do following to select 'active' news item:

```
$news = $newsStore
        ->orderBy( 'asc', 'order' )
        ->where( 'startDate', '<', time() )
        ->where( 'endDate', '>', time() )
        ->fetch();
```

Looks like first condition is completely ignored and only second one is applied.

Any help please?

**Comment by typomedia** [comment]
Got the same issue!

**Comment by lukasznowicki** [comment]
@snoopy4ever @typomedia @rakibtg  Guys, here is the solution for this problem - https://github.com/rakibtg/SleekDB/pull/23

I also forked (to create PR) this repository and merged that fix - https://github.com/lukasznowicki/SleekDB

**Comment by snoopy4ever** [comment]
Nice one mate 👍 
Dzieki Lukasz 🥇

**Comment by rakibtg** [comment]
@lukasznowicki thanks for the contribution, appreciate that you take the time and to fix the issue. I will merge your PR today!

**Comment by thecosss** [comment]
> @lukasznowicki thanks for the contribution, appreciate that you take the time and to fix the issue. I will merge your PR today!

So where is the merge?!

**Comment by thecosss** [comment]
@lukasznowicki Didn't worked for me. I copied your src/traits/helpers.php but the bug is still there (

**Comment by rakibtg** [comment]
@snoopy4ever I think you should use `orWhere` like this:
```
$news = $newsStore
        ->orderBy( 'asc', 'order' )
        ->where( 'startDate', '<', time() )
        ->orWhere( 'endDate', '>', time() )
        ->fetch();
```

**Comment by rakibtg** [comment]
I will close the issue here, feel free to post a comment and re-open it.
