### ISSUE TITLE
SleekDB permission issue

### ISSUE THREAD

**Issue by jeffshead** [rakibtg/SleekDB#220]
I host my own Linux web server. I have multiple domains and each domain is a separate Linux user. I have a small, simple web app which will use SleekDB. The web app will be hosted on a single domain but it will be used across different domains. I have a PHP file which can be included on any web page, on any of my self-hosted domains. On the pages where this file is included, I capture user info which is written to the single SleekDB database. So this means multiple users will need to utilize the same SleekDB database.

If I manually install SleekDB and keep the default permissions, I get the following errors when accessing from a different domain: 

```
[Thu Sep 23 07:40:45.570661 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] PHP Fatal error:  Uncaught SleekDB\\Exceptions\\IOException: Directory or file is not writable at "/home/USER1/public_html/DBapp/mydatabase/users/_cnt.sdb". Please change permission. in /home/USER1/public_html/DBapp/src/Classes/IoHelper.php:29
[Thu Sep 23 07:40:45.570790 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] Stack trace:
[Thu Sep 23 07:40:45.571074 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] #0 /home/USER1/public_html/DBapp/src/Classes/IoHelper.php(142): SleekDB\\Classes\\IoHelper::checkWrite('/home/USER1/...')
[Thu Sep 23 07:40:45.571372 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] #1 /home/USER1/public_html/DBapp/src/Store.php(854): SleekDB\\Classes\\IoHelper::updateFileContent('/home/USER1/...', Object(Closure))
[Thu Sep 23 07:40:45.571588 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] #2 /home/USER1/public_html/DBapp/src/Store.php(814): SleekDB\\Store->increaseCounterAndGetNextId()
[Thu Sep 23 07:40:45.571821 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] #3 /home/USER1/public_html/DBapp/src/Store.php(145): SleekDB\\Store->writeNewDocumentToStore(Array)
[Thu Sep 23 07:40:45.571997 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] #4 /home/USER1/public_html/DBapp/inserter.php(47): SleekDB\\Store->insert(Array)
[Thu Sep 23 07:40:45.572160 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] #5 /home/USER2/public_html/index.php(2): include('/home/USER1/...')
[Thu Sep 23 07:40:45.572189 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798] #6 {main}
[Thu Sep 23 07:40:45.572365 2021] [:error] [pid 26109:tid 140364455290624] [client 192.168.1.20:60798]   thrown in /home/USER1/public_html/DBapp/src/Classes/IoHelper.php on line 29
```

The simple solution is to recursively cmod the SleekDB database directory to 0777 after it has been created. As a feature, can this be done automatically when the SleekDB store is created? Maybe implement a new variable such as $crossdomain or $multiuser. If true, chmod the proper directories/files to 0777 or to whatever the permissions should be.

If you think this is not a worthwhile feature, can you please post a PHP code example of how I can do this safely?

**Comment by redaloui** [comment]
@jeffshead 
Hi,
I did that by simply send get or post to the remote server.
Also you can do it via ajax, if you are using it already to post form data.
For the permissions,  indeed, I didnt got that issue, cause SleekDB do that. But may be it is related to your server config.
But anyway, you can cmod easily with php if needed.
https://www.php.net/manual/en/function.chmod.php

**Comment by Timu57** [comment]
Sounds like a great idea to implement a configuration, that allows the user to control the folder and file permissions.

**Comment by Jakiboy** [comment]
I'm experiencing the same issue, I would like the possibility of implementing a configuration for that,

**Comment by Timu57** [comment]
@Jakiboy Thank you for your contribution :heart:
