### ISSUE TITLE
findBy not working when searching for an integer field

### ISSUE THREAD

**Issue by sanmayad** [rakibtg/SleekDB#221]
Hey

if bind parameter is like following no result is shown for findBy
`[['author_id','=',25]]`

Please make me understand, do I need to typecast or anything?

**Comment by Timu57** [comment]
Hi @sanmayad 
the condition '=' is type safe. It is an alias for '==='.
You can use '==' to make a type unsafe comparison.
https://sleekdb.github.io/#/criteria

**Comment by sanmayad** [comment]
okay, understood thanks :)
