### ISSUE TITLE
fetching document without a field

### ISSUE THREAD

**Issue by yssunjoko** [rakibtg/SleekDB#222]
Hi guys,
some documents in my store have a boolean field `is_deleted` while some others do not.
How can the documents without the field be fetched out?
I know this should be simple.

```
...
$store = new \SleekDB\Store($storeName, $dbPath, $config);
$docs = $store->findBy(["is_deleted", ....🙄🙄🙄]); // what to write here to make it fetch only the documents without the `is_deleted` field
```

Thank you for any helpful suggestion.

**Comment by Timu57** [comment]
@yssunjoko 
I just remembered.
You can always use closures to use custom functionality.
Just like in Example 4 on this page: https://sleekdb.github.io/#/criteria

```php
$store->findBy([
  function($document){
    return isset($document['is_deleted']);
  }
]);
```

**Comment by Timu57** [comment]
With [version 2.13](https://github.com/rakibtg/SleekDB/releases/tag/2.13) we introduced the new "EXISTS" condition to check for fields.
Feel free to reopen this issue if needed.
