### ISSUE TITLE
CRUD API like semation.com

### ISSUE THREAD

**Issue by KoljaL** [rakibtg/SleekDB#225]
Hello Kazi & Timucin,
thank you very much for the work you have done with SleekDB!   
The idea of storing data in JSON files is as simple as it is ingenious. 

For my next application, I would like to build on it. But since the frontend is designed with Vue,  
I still need an API to get the data via URL request from my webserver. 
The docs don't say anything about an API and a quick search only resulted in this page: https://semation.com/.
Unfortunately without any reference to the source code.

So my question: Is there (somewhere) a CRUD API for  SleekDB?

Additionally, I would be interested in the future of SleekDB.   
Are there any big changes planned that are worth waiting for?

Kind regards Kolja

**Comment by Timu57** [comment]
Hi @KoljaL 
Thank you for your interest.
Currently SleekDB has no ready to use API implementation.
You can use SleekDB as a "in software database".
With SleekDB you can build your own API backend.
I am currently working on a headless CMS using SleekDB.
When it's finished, you will be able to use that as an API backend powering your Software.

**Comment by KoljaL** [comment]
Hi @Timu57
Thank you for your answer. 
In the meantime, I have read a little more about SleekDB and have developed my project further.   
I probably don't need a "real" API, but exactly what you meant by "software database". 

I'm curious about your CMS, is there already a pre-release?
