### ISSUE TITLE
InvalidArgumentException: Order has to be a string!

### ISSUE THREAD

**Issue by s427** [rakibtg/SleekDB#227]
Hi,

I'm just starting using SleekDB and ran into this problem:

The following request runs fine:
`$data = $mainDb->findAll();`

However when I try to add parameters:
`$data = $mainDb->findAll([["name" => "desc"], 1, null]);`

I get the following error message:

Fatal error: Uncaught SleekDB\Exceptions\InvalidArgumentException: Order has to be a string! Please use "asc" or "desc" only. in \SleekDB\QueryBuilder.php:209
Stack trace:
#0 \SleekDB\Store.php(225): SleekDB\QueryBuilder->orderBy(Array)
#1 \server.php(70): SleekDB\Store->findAll(Array)
#2 {main} thrown in \SleekDB\QueryBuilder.php on line 209

What am I doing wrong?
Thanks for your help.

**Comment by Timu57** [comment]
Hi @s427 
You used the method wrong.
`findAll` does have 3 optional parameters. https://sleekdb.github.io/#/fetch-data#findAll

The problem is, that you used just one array.

In your case right usage would look something like this:
```php
$data = $mainDb->findAll(["name" => "desc"], 1);
```
