### ISSUE TITLE
Math & Logic operations

### ISSUE THREAD

**Issue by blessedjasonmwanza** [rakibtg/SleekDB#233]
Is it possible to implement math operations such as SUM, AVG, and MIN?

I am planning on adopting SleekDB for our DB infrastructure, however - I can't seem to find some special and/or aggregate functions documented. Any help will be appreciated on this.

**Comment by Timu57** [comment]
Hello @blessedjasonmwanza
You can use the select method of the QueryBuilder to use "select functions".

In addition to the build in functions like CONCAT, SUM, AVG and more, you can easily implement "custom functions".

You can see the usage in the examples and if you need more help or advice feel free to join the discord.

Link to the select documentation:
https://sleekdb.github.io/#/query-builder#select

**Comment by blessedjasonmwanza** [comment]
Thanks a lot, @Timu57 👨🏽‍💻 

> HappyCoding 💻
