### ISSUE TITLE
nested column select and distinct return empty array

### ISSUE THREAD

**Issue by REDAL** [rakibtg/SleekDB#236]
@Timu57  @rakibtg  @robkellas  @daussho 

Hi SleekDB Team,

I am trying to retrieve data from a 2-dimensional array

data array in json file :

"cquantCli": [
        {
            "cprcCli": "47",
            "camo": "48",
            "ctyp": "1",
            "cdsc": "49"
        },
        {
            "cprcCli": "50",
            "camo": "51",
            "ctyp": "2",
            "cdsc": "52"
        }
    ]

my query :           ->select(["cli" => "cquantCli.cprcCli"])

I am expecting : 

[["_id" => 1, "cli" => 47], ["_id" => 2, "cli" => 50]]

it returns ; 

Array
(
    [0] => Array
        (
            [_id] => 1
            [cli] => 
        )

)

The same goes for distinct function, does not work for nested query

help please,
kindest regards

**Comment by Timu57** [comment]
Hi @REDAL
your query is wrong for your data-structure. Like we discussed in discord you can use custom select functions to query the cquantCli array.
I will close this issue for now, feel free to reopen it if needed :blush:

**Comment by Timu57** [comment]
@REDAL I know, I just repeated the solution/answer here for people having a similar problem :)
