### ISSUE TITLE
How to Run SleekDB

### ISSUE THREAD

**Issue by SmpManeth** [rakibtg/SleekDB#240]
I'm New to SleekDB. How to run the DB? 
Please Can someone give me Assistance with learning in sleekdb?

**Comment by Timu57** [comment]
Hi @SmpManeth welcome to sleekdb :)
I would recommend to join our discord server. There are many veterans who love to help newcomers :) 

https://discord.gg/WJGqUFPtZw

Regardless of that, you just need to follow the documentation 😊 
And if you encounter problems you are welcome to ask for help on discord.

**Comment by jholmes001** [comment]
I just set this up today and found it extremely easy. The documentation is easy to follow here: https://sleekdb.github.io/.

**Comment by REDAL** [comment]
> I'm New to SleekDB. How to run the DB? Please Can someone give me Assistance with learning in sleekdb?

Just include store.php
and add names spaces above the PHP file
use SleekDB\Store, SleekDB\Query;

as mentioned above, its super easy, just follow the documentation
https://sleekdb.github.io/

regards

**Comment by SmpManeth** [comment]
Thank you So much guys. I found the Documentation very usefull.
