### ISSUE TITLE
Class 'SleekDB\Store' not found

### ISSUE THREAD

**Issue by FunWithAlbiYT** [rakibtg/SleekDB#247]
`Fatal error: Uncaught Error: Class 'SleekDB\Store' not found in /home/runner/projx/index.php:23 Stack trace: #0 {main} thrown in /home/runner/projx/index.php on line 23`

I used composer to install and this is line 21, 22, 23, and 24:
![image](https://user-images.githubusercontent.com/68329886/208230056-8748171c-b3ee-4404-b21a-df5a55f97515.png)

**Comment by Timu57** [comment]
Hi @FunWithAlbiYT 
Thank you for your report.

Can you show me how you imported SleekDB? The error indicates that SleekDB is missing.

If you used a use statement you probably just need to write `new Store()`. Without the `SleekDB` part.

**Comment by FunWithAlbiYT** [comment]
It's fixed now I don't really know how.
