### ISSUE TITLE
->where()->where() works like a OR condition

### ISSUE THREAD

**Issue by jpsarda** [rakibtg/SleekDB#25]
Love this library. I think the ->where()->where()  conditions works like an **OR** condition.
I've added this line to make it work as I expected (as a **AND** condition) in helpers.php. 

[edit] not exactly a OR condition, it's the last where clause that decides if the conditiosn are OK.

```
if( $validData === true ) {
        $storePassed = $this->verifyWhereConditions( $condition[ 'condition' ], $fieldValue, $condition[ 'value' ] );
        if (!$storePassed) break; //added by JP,  bug ?
}
```

**Comment by rakibtg** [comment]
Hi @jpsarda Can you show some demo data with the query you are using so I can easily reproduce this issue?

Thanks

**Comment by ostankin** [comment]
I think I can. Just stumbled upon the same problem, pretty similar to https://github.com/rakibtg/SleekDB/issues/22. I checked out version 1.5.1, but it reproduces there as well.

Here is my code:

```
<?php
require_once "SleekDB/SleekDB.php";

$dataDir = "../db";
$storeName = "test-store";
$store = \SleekDB\SleekDB::store($storeName, $dataDir);

$records = array(
  [
    'timestamp' => 1000,
    'stars' => 1
  ],
  [
    'timestamp' => 2000,
    'stars' => 2
  ],
  [
    'timestamp' => 4000,
    'stars' => 4
  ]
);

$store->delete();
foreach ($records as $record) {
  $store->insert($record);
}

$start = 3000;
$end = 5000;
$result = $store
  ->orderBy('asc', 'timestamp')
  ->where('timestamp', '>=', $start)
  ->where('timestamp', '<=', $end)
  ->fetch();
$stars = array();
foreach ($result as $record) {
  array_push($stars, $record['stars']);
}

print_r($stars);
?>
```

This code creates three records with three timestamps (I made them small and round for simplicity). Then I made a query that is expected to return only the last record, whrere `stars` equals `4`. However, the query returns all records:
```
﻿Array
(
    [0] => 1
    [1] => 2
    [2] => 4
)
```

**Comment by ostankin** [comment]
Ok, my bad - I messed up the versions. Version `1.5.1` indeed fixes the issue. Sorry, disregard the above.
