### ISSUE TITLE
Searching for value in array.

### ISSUE THREAD

**Issue by Norren** [rakibtg/SleekDB#252]
I've run into a bit of a puzzle that doesn't seem to be in the documentation, or if it is it's written in a way that eludes my inexperienced grasp: I'm attempting to find a number in an array using Query builder and Search().

Simplified example:
{name: "user", _id: 13, tokens: [33, 44, 55]}

All the examples seem to assume you're search for a known string, not a value in an array such as "tokens", 44  Is this just a design error on my part, am I overlooking the instructions, or should I just be doing a findAll() and using a foreach loop to array search each result's token field individually?

**Comment by Timu57** [comment]
Hi @Norren thank you for your interest and question.

Does the CONTAINS condition do what you want?

https://sleekdb.github.io/#/criteria

**Comment by Norren** [comment]
Ahah!  There we go, thank you very much!
