### ISSUE TITLE
How to set special chars?

### ISSUE THREAD

**Issue by JTorresConsulta** [rakibtg/SleekDB#257]
Hi, I am so happy to found your amazing project.  

I am from Spain and I need to insert names with accent marks, for example "María" or "Toño".

But SleekDB saved as "Mar\u00eda" and "To\u00f1o"

Thank you!

**Comment by Timu57** [comment]
Hi @JTorresConsulta thank you for your kind words.
Do you get a wrong result when using the build in methods to retrieve the data?

**Comment by JTorresConsulta** [comment]
Hi @Timu57   thanks

I am writing data like the next:

```
$Store = new Store("codes", $databaseDirectory, $storeConfiguration);

 $codes = [
    [
      "code" => RandCode(6),
      "owner" =>[
          "name" => "María",
           ....
        ],	  
      ]	  
  ];

$codes = $Store->insert($codes);
```



I am retrieving data like documentation, for example like this: (but all methods return bad chars)

```
$row = $Store->findAll();
echo json_encode($row, JSON_PRETTY_PRINT); 
```

It print the next:

```
  [
    {
        "0": {
            "code": "R1XT74",
            "owner": {
                "name": "Mar\u00eda",
                ....
            }
        },
        "_id": 1
    }
]

```

**Comment by JTorresConsulta** [comment]
Russian or Greek alphabet chars are also displayed with unicode

For example:

"Λ" shows  \u039b
"Γ" shows  \u0393
"Ξ" shows  \u039e
...

**Comment by JTorresConsulta** [comment]
Wait @Timu57. I think is not a bug.

The unicode return is showed only in the JSON encode array list.
In the decoded JSON the name is showed correctly:


```
  $data = json_decode($row);
  echo  "name--> ".$row[0]["0"]['owner']['name']; 
```

It print the next:
`"name-->María"`

**Comment by Timu57** [comment]
Hi @JTorresConsulta I tried to reproduce the bug.
It seems like everything is working fine.
![grafik](https://github.com/rakibtg/SleekDB/assets/28825283/d69a5922-718d-4e60-9417-e32eb2383bdd)
![grafik](https://github.com/rakibtg/SleekDB/assets/28825283/012563ba-1c71-4032-a631-d1f47a3fe827)

`var_dump` and `print_r` return the correct characters.

![grafik](https://github.com/rakibtg/SleekDB/assets/28825283/98722b9b-83fb-4dcf-b3c1-8c1c138a56f2)

I would say that using `json_encode` causes the problem you have.

**Comment by JTorresConsulta** [comment]
Exactly @Timu57 

Was my error using  "json_encode"

The problem is solved if i try with 

`json_encode($row, JSON_UNESCAPED_UNICODE); `

Please excuse me ! thank you for the support and the good work <3

**Comment by Timu57** [comment]
@JTorresConsulta Great that I could help you :) Feel free to open a new issue if you encounter a new bug.
Consider joining our Discord Server if you want/ need any help.
