### ISSUE TITLE
updateById method undefined

### ISSUE THREAD

**Issue by sistemanick** [rakibtg/SleekDB#259]
According to the docs I should be able to call updateById on the store, but I'm getting the following error instead:
Call to undefined method SleekDB\SleekDB::updateById()

Here's the sample code:
```
$db = SleekDB::store('students', 'data');

$data = ['name' => 'John Jones'];
$id = 1;
$db->updateById($id, $data);
```

**Comment by elialum** [comment]
Use updateOrInsert, put the id in the array 

```
$db = SleekDB::store('students', 'data');

$data = array(
'_id' => 1,
'name' => 'John Jones',
);

$db->updateOrInsert($data);
```

**Comment by sistemanick** [comment]
Same error:
Call to undefined method SleekDB\SleekDB::updateOrInsert()

Note that I've also tried the "update" method, but no matter what _id I put in the data array, the method updates ALL records, which is very very bad. For example:

```
$data = $db->findById(2);
$data['name'] = 'Jane Smith';
$db->update($data);
```

Instead of updating the record with _id = 2, it updates the name of all records to "Jane Smith".

**Comment by Timu57** [comment]
Hi @sistemanick as shown in https://sleekdb.github.io/#/getting-started you need to use `SleekDB\Store` not `SleekDB\SleekDB`, which is only for backwards compatibility.

I will close this issue for now. Please feel free to reopen it if needed :blush:
