### ISSUE TITLE
Great work! (suggestion, not an issue)

### ISSUE THREAD

**Issue by venkycc** [rakibtg/SleekDB#27]
Looks like a mini_mongo db :-)
Each record is stored in a json file with an indexed value starting from 1. It will be nice to have a custom prefix to this... dynamically.

For example, i would prefer to prefix it with a username so that whenever i am in a hurry, i can open the related .json file straightaway instead of doing a find or instead of using sleekdb to find it

Is this doable?

**Comment by rakibtg** [comment]
Hi @venkycc At this moment it's not doable, but it is possible. Noted! 
Thanks
