### ISSUE TITLE
How to delete data from a doc?

### ISSUE THREAD

**Issue by thecosss** [rakibtg/SleekDB#28]
![image](https://user-images.githubusercontent.com/4847308/74590011-37dc3300-5013-11ea-9de2-44d8c5c511b1.png)
I have messed up my doc, how can I delete keys from 1 to 19?

**Comment by rakibtg** [comment]
You can use the `update` method! 
Example:
```
$store->where( 'chat_id', '=', '6679...' )->update( $updateable );
```
If this was not the solution you were looking for, please add more details in your question!

**Comment by thecosss** [comment]
> You can use the `update` method!
> Example:
> 
> ```
> $store->where( 'chat_id', '=', '6679...' )->update( $updateable );
> ```
> 
> If this was not the solution you were looking for, please add more details in your question!

Ok, but what should be in $updateable in my case?
I've tried this and that didn't work
`$res2 = $workersStore->where('chat_id', '=', '66797039')->fetch();
unset($res2[0]['1']);
unset($res2[0]['2']);
unset($res2[0]['3']);
unset($res2[0]['4']);
unset($res2[0]['5']);
unset($res2[0]['6']);
unset($res2[0]['7']);
unset($res2[0]['8']);
unset($res2[0]['9']);
unset($res2[0]['10']);
unset($res2[0]['11']);
unset($res2[0]['12']);
unset($res2[0]['13']);
unset($res2[0]['14']);
unset($res2[0]['15']);
unset($res2[0]['16']);
unset($res2[0]['17']);
unset($res2[0]['18']);
unset($res2[0]['19']);
$workersStore->where('chat_id', '=', '66797039')->update($res2);`

**Comment by rakibtg** [comment]
@thecosss You can do something like this:
```PHP
// Find the document.
$res2 = $workersStore->where('chat_id', '=', '66797039')->fetch();
// Rearrange the data set.
$updatable = [
  "name" => $res2["name"],
  "chat_id" => $res2["chat_id"],
  "idle" => $res2["idle"],
  "level" => $res2["level"],
  "tasks" => $res2["tasks"],
  "balance" => $res2["balance"],
  "activated" => $res2["activated"]
];
// Update the document.
$workersStore->where('chat_id', '=', '66797039')->update($res2);
```
Hope it helps!

**Comment by thecosss** [comment]
> @thecosss You can do something like this:
> 
> ```
> // Find the document.
> $res2 = $workersStore->where('chat_id', '=', '66797039')->fetch();
> // Rearrange the data set.
> $updatable = [
>   "name" => $res2["name"],
>   "chat_id" => $res2["chat_id"],
>   "idle" => $res2["idle"],
>   "level" => $res2["level"],
>   "tasks" => $res2["tasks"],
>   "balance" => $res2["balance"],
>   "activated" => $res2["activated"]
> ];
> // Update the document.
> $workersStore->where('chat_id', '=', '66797039')->update($updatable);
> ```
> 
> Hope it helps!

Well, update($updatable) doesn't remove those keys, it just updates indicated keys

**Comment by rakibtg** [comment]
@thecosss Can you show me your code snippet of inserting this data?

**Comment by thecosss** [comment]
I don't have it but it was exactly like yours. Also I don't have this problem any more since I've deleted the doc and inserted new one.

**Comment by rakibtg** [comment]
@thecosss Glad you fixed it! I will close the issue.
