### ISSUE TITLE
Possibility of duplicate ID’s

### ISSUE THREAD

**Issue by joemottershaw** [rakibtg/SleekDB#30]
If 2 data arrays were inserted into a store/table from separate requests at exactly the same time, for example 2 comments from 2 different users. What would stop these inserts from using the same ID?

I know the probability is unlikely but is there a system in place to prevent this?

I did look to see if `flock` was used but couldn’t find anything.

**Comment by rakibtg** [comment]
@joemottershaw The unique ID is being generated from this method: https://github.com/rakibtg/SleekDB/blob/master/src/traits/helpers.php#L121-L131

File locking and waiting functionalities will be added in the next version.
