### ISSUE TITLE
OR Condition Query

### ISSUE THREAD

**Issue by petrfilip** [rakibtg/SleekDB#31]
Hi Hasan, I am very exciting about your SleekDB project. I started to using it to build simple headless CMS. And the orWhere is little bit limitating to me. I would like to use construction such as `Where(firstCondition)->Or(anotherCondition, anotherOneCondition)`. I think, actually something like this is not possible to do it in one query. What do you think about the idea? 

If you like it, I can do it (but I need a little chance that you will merge it into your project :-D )

**Comment by rakibtg** [comment]
@petrfilip That sounds great! 
Please send a PR and also if you need any help from me feel free to post a reply here.
