### ISSUE TITLE
Open and import existing json-files

### ISSUE THREAD

**Issue by NoBodyButMe** [rakibtg/SleekDB#33]
May sound as a stupid question, but how can I read and edit existing JSON files?

**Comment by rakibtg** [comment]
Please follow the documentation at https://sleekdb.github.io/
- [Fetch](https://sleekdb.github.io/#fetch-data) to read data
- [Edit](https://sleekdb.github.io/#edit-data) to update data
- [Delete](https://sleekdb.github.io/#delete-data) to delete data

Please re-open this issue with the code example that you are facing trouble with.
