### ISSUE TITLE
Like Condition

### ISSUE THREAD

**Issue by haan78** [rakibtg/SleekDB#34]
I added these lines into the 
HelpersTrait->verifyWhereConditions

else if ( $condition === "like" ) {
        if ( strpos($fieldValue,$value) === false ) return false;
      }
it looks fine.

**Comment by rakibtg** [comment]
I think using regular expression instead of `strpos` would be a better idea to mimic the behaviour of the `LIKE` clause.

**Comment by Timu57** [comment]
#40 new Like-Condition, implemented with regular expressions and preg_match

**Comment by Timu57** [comment]
The like condition now supports all wildcards shown in https://www.w3schools.com/sql/sql_wildcards.asp at **Wildcard Characters in SQL Server**
