### ISSUE TITLE
Supress Key on fetch

### ISSUE THREAD

**Issue by brunogrenier** [rakibtg/SleekDB#38]
**Not show** some keys on fetch.

**1- have a store:**

[
{
"name":"Bruno",
"country":"Brazil",
"age":"35",
"_id":1
},
{
"name":"Hasan",
"country":"Bangladesh",
"age":"30",
"_id":2
},
{
"name":"XYZ",
"country":"Z",
"age":"20",
"_id":3
},
{
"name":"ABC",
"country":"C",
"age":"10",
"_id":4
}
]

**2- Fetch supressing keys "age" and "id":**

$store= \SleekDB\SleekDB::store("example", dirname(__FILE__)."/dataBase");
$result = $store->where("_id",<",3)->**SUPRESS("age","_id")**->fetch();

**3- Expected fetch result:**
$result =
[
{
"name":"Bruno",
"country":"Brazil"
},
{
"name":"Hasan",
"country":"Bangladesh"
}
]

**Comment by rakibtg** [comment]
Added in [SleekDB 2.0](https://github.com/rakibtg/SleekDB/releases/tag/2.0)!
