### ISSUE TITLE
Saving format is wrong

### ISSUE THREAD

**Issue by REDAL** [rakibtg/SleekDB#39]
**When trying to insert data using insert command**

It saves data like this :
![image](https://user-images.githubusercontent.com/7544360/94039790-6fd8ff00-fdc8-11ea-92f8-4643b1987f40.png)

instead of this:
![image](https://user-images.githubusercontent.com/7544360/94039807-75364980-fdc8-11ea-94da-f79e5eea94f4.png)

so, when I am trying to fetch data with conditions like (where, in) it returns an empty array.

thanks

**Comment by rakibtg** [comment]
@REDAL 
To insert:
```php

  // Initial store creation.
  $myStore = \SleekDB\SleekDB::store('myStore', __DIR__.'/db');

  // Insert data.
  $myStore->insert([
    'email' => "contact@google.com",
    'pass' => "123",
    'fname' => "foo",
    'lname' => "bar"
  ]);
```
Data will be inserted like this:
```json
{
  "email": "contact@google.com",
  "pass": "123",
  "fname": "foo",
  "lname": "bar",
  "_id": 1
}

```
Applying where condition:
```php
  $myStoreData = $myStore
    ->where('email', '=', 'contact@google.com')
    ->fetch();
```

Documentation available here: https://sleekdb.github.io/

**Comment by REDAL** [comment]
**### Thank you Mr Hasan,  for the reply, it works fine now.
have a nice day and be safe**
