### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by thecosss** [rakibtg/SleekDB#4]
`require_once "../SleekDB/SleekDB.php";
$db = new \SleekDB\SleekDB( "../mydb" );
$ordersStore = $db->store('orders');
$tasksStore = $db->store('tasks');
$workersStore = $db->store('workers');`

When I print_r $ordersStore or $tasksStore it actually prints workersStore
If i comment $workersStore variable assign it will print tasksStore and so on.

**Comment by rakibtg** [comment]
Hi @thecosss 
Have you installed it using composer?
Can you show me your code? because i cant re-produce the bug!

**Comment by rakibtg** [comment]
@thecosss Here is a quick fix, 
```
  $db->store('orders')->insert([
    'order_id' => '92837483',
    'items' => ['coco', 'test', 'foo']
  ]);

  $db->store('tasks')->insert([
    'task_id' => '354545',
    'detail' => 'Foo Bar'
  ]);

  $db->store('workers')->insert([
    'worker_id' => '141414',
    'name' => 'Dan'
  ]);
```
Instead of using the variable always use the `$db` instance to access and insert data into the store.

**Comment by rakibtg** [comment]
@thecosss This bug is now fixed, `store` is now a static method in the new api. So you can do this:
```php
  $dataDir = "../mydb";
  
  $ordersStore = \SleekDB\SleekDB::store('orders', $dataDir); 
  $tasksStore = \SleekDB\SleekDB::store('tasks', $dataDir); 
  $workersStore = \SleekDB\SleekDB::store('workers', $dataDir);
```
Take a look at the updated doc: https://sleekdb.github.io/#getting-started
