### ISSUE TITLE
Return distincted value

### ISSUE THREAD

**Issue by wuspum** [rakibtg/SleekDB#41]
Is there an option to fetch distincted single values?

For example $store->select('name')->distinct()->where(...)->fetch();

**Comment by rakibtg** [comment]
@wuspum Added distinct feature!

Example:
```php
$userStore->distinct('name')->distinct(['country', 'foobar'])->fetch();
```

Available in `dev` at this moment.

**Comment by rakibtg** [comment]
Added in [SleekDB 2.0](https://github.com/rakibtg/SleekDB/releases/tag/2.0)!
