### ISSUE TITLE
Cache based on key

### ISSUE THREAD

**Issue by brunogrenier** [rakibtg/SleekDB#43]
Its possible to create automatic cache based on key?

**Define AUTOMATIC CACHE for Key "country" on store $members.**

The idea is all distinct values on key "country" (Brazil, Bangladesh, Z, C) would have automatic cache for fast fetch.
(each data update, would update automatically the cached data)

Example:
1- have a store $members=

[
{
"name":"Bruno",
"country":"Brazil",
"age":"35",
"_id":1
},
{
"name":"Hasan",
"country":"Bangladesh",
"age":"30",
"_id":2
},
{
"name":"XYZ",
"country":"Z",
"age":"20",
"_id":3
},
{
"name":"ABC",
"country":"C",
"age":"10",
"_id":4
},
{
"name":"User 5",
"country":"Brazil",
"age":"36",
"_id":5
},
{
"name":"User 6",
"country":"Bangladesh",
"age":"37",
"_id":6
}
]

**Comment by rakibtg** [comment]
Hi @brunogrenier, I'm not sure if this will be possible at this moment, the entire caching mechanism depends on the query chain, the generated _id field has no effect here.

I will close this issue, feel free to reopen.

**Comment by brunogrenier** [comment]
It is OK!
SleekDB is awesome!!!

________________________________
De: Kazi Mehedi Hasan <notifications@github.com>
Enviado: quarta-feira, 21 de outubro de 2020 18:39
Para: rakibtg/SleekDB <SleekDB@noreply.github.com>
Cc: brunogrenier <brunogrenier_cwb@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [rakibtg/SleekDB] Cache based on key (#43)


Hi @brunogrenier<https://github.com/brunogrenier>, I'm not sure if this will be possible at this moment, the entire caching mechanism depends on the query chain, the generated _id field has no effect here.

I will close this issue, feel free to reopen.
