### ISSUE TITLE
Extend not possible due to private helper methods

### ISSUE THREAD

**Issue by einicher** [rakibtg/SleekDB#44]
Hello, please consider to make the private helper methods protected. It is not possible to extend SleekDb this way. After setting `bootStore` and `initVariables` from private to protected i was able to extend, but also had to copy the whole store method:

```php
class LibreSleekDb extends \SleekDB\SleekDB
{
	public static function store( $storeName = false, $dataDir, $options = false ) {
		if ( !$storeName OR empty( $storeName ) ) throw new \Exception( 'Store name was not valid' );
		$_dbInstance = new LibreSleekDb( $dataDir, $options );
		$_dbInstance->storeName = $storeName;
		// Boot store.
		$_dbInstance->bootStore();
		// Initialize variables for the store.
		$_dbInstance->initVariables();
		return $_dbInstance;
	}

	public function fetch()
	{
		$results = parent::fetch();
		foreach ($results as $key => $result) {
			$results[$key] = (object) $result;
		}
		return $results;
	}
}
```
Now i can do `LibreSleekDb::store('articles', $dataDir);`

**Comment by rakibtg** [comment]
Can you tell me a little more about this use case, why you wanted to extend it instead of initialising it directly inside the `LibreSleekDb` class?

**Comment by einicher** [comment]
I guess thats how I am used to handle oop. I need to extend the functionality of SleekDB methods and add some new ones. So i extend and overwrite them. Original api stays intact (and is well documented) but gets additional features as I need them. In this first case I needed fetch to return objects, not assoc arrays.

**Comment by rakibtg** [comment]
@einicher Thanks for the details, I will look into it. If you have any further input on this in the mean time let me know.

**Comment by Timu57** [comment]
We refactored and rewrote the whole project. Possible that it now suites your needs. I will close this issue. Feel free to reopen it if needed.
