### ISSUE TITLE
Like operator not in packagist version?

### ISSUE THREAD

**Issue by einicher** [rakibtg/SleekDB#46]
This like operator does not seem to be available in SleekDB installed by composer:

https://github.com/rakibtg/SleekDB/blob/9f4c2d95fcb7871955c066dc455a52165d2099dd/src/Traits/HelperTrait.php#L237

how come?

**Comment by Timu57** [comment]
Hi,
I think the owner wants to implement the join feature before releasing a new version with the recently made updates.

If you want the latest and greatest without waiting, just type the following command to get the dev-master branch version:

```bash
composer require rakibtg/sleekdb dev-master
```

**Comment by rakibtg** [comment]
Yes indeed, thanks @Timu57. I am working on the documentation page (content+redesign). I will try my level best to publish it soon by releasing with a new version tag.
<img width="1552" alt="Screenshot 2020-11-11 at 11 18 28 PM" src="https://user-images.githubusercontent.com/5412730/98842889-6721b280-2474-11eb-9bd3-4b020fa05c70.png">
