### ISSUE TITLE
Date Rang

### ISSUE THREAD

**Issue by ajoudeh** [rakibtg/SleekDB#47]
Hi,

Is Date  Range filter supported or not?

Thanks,

**Comment by Timu57** [comment]
Hi,
the BETWEEN functionality is not implemented yet but it is a good idea.

You can use a combination of the greater and less conditions as an alternative.

For example:
```php
$articleDB
  ->where( 'date', '>', $dateBegin )
  ->where( 'date', '<', $dateEnd )
  ->fetch();
```

**Comment by ajoudeh** [comment]
Im using this combination but it is not working.

**Comment by ajoudeh** [comment]
And is it working if the time exist?
Sample json

{"FacilityId":"02","User_id":"0834505","Parent_desc":null,"Status":null,"Event_date":"2020-09-14 17:54","_id":68}

**Comment by Timu57** [comment]
It should work if you save a timestamp instead of a string.

https://www.php.net/manual/de/datetime.gettimestamp.php
```php
<?php
$date = new DateTime("2020-09-14 17:54");
$eventDate = $date->getTimestamp();
?>
```
alternatively in one line:
```php
$eventDate = (new DateTime("2020-09-14 17:54"))->getTimestamp();
```

Later you can convert it back to a string like this:

https://www.php.net/manual/de/datetime.format.php
```php
$eventDate = (new DateTime($timestamp))->format("'Y-m-d H:i");
```

**Comment by ajoudeh** [comment]
Ok I will try this solution.
Thanks,
