### ISSUE TITLE
Conditions are not reset

### ISSUE THREAD

**Issue by dima-stefantsov** [rakibtg/SleekDB#5]
Hi. I'm trying to use SleekDB like shown in manual.

```
$db_codes = \SleekDB\SleekDB::store('bonus_codes', PATH_DB, [
    'auto_cache' => false,
    ]);

$code1 = $db_codes->where('code', '=', $raw_code1)->fetch();
$code2 = $db_codes->where('code', '=', $raw_code2)->fetch();
$codes_all = $db_codes->fetch();
```

$code1 have one item, like it should. $code2 have 0 items, while it should have 1, $codes_all have 0 items, totally unlike it should.

I have looked through the code and I can see it's because on every -> where() call, local variable conditions[] are appended. Conditions have stacked through the calls, this is why just pure $db_codes->fetch() gives 0 results.

From my understanding, **this is not how it's supposed to work**. I expect $db_codes->where() not to modify initial $db_codes instance, but maybe create a copy. Or maybe conditions should be reset on every ->fetch() call.

How am I supposed to find items in foreach()? Create a new instance of $db_codes every time?
I have found https://github.com/rakibtg/SleekDB/issues/4 issue, where you give example code 
```
 $db->store('orders')->insert([
    'order_id' => '92837483',
    'items' => ['coco', 'test', 'foo']
  ]);
```

If I'd create a new store for every query, that will obviously work. But that's not how you have it in your manual. I'd like to do it like your manual states.

Instead of 
```
$db = new \SleekDB\SleekDB(PATH_DB, ['auto_cache' => false]);
$code1 = $db->store('bonus_codes', PATH_DB, ['auto_cache' => false])->where('code', '=', $raw_code1)->fetch();
$code2 = $db->store('bonus_codes', PATH_DB, ['auto_cache' => false])->where('code', '=', $raw_code2)->fetch();
$codes_all = $db->store('bonus_codes', PATH_DB, ['auto_cache' => false])->fetch();
```

It should be possible to just
```
$db = new \SleekDB\SleekDB(PATH_DB, ['auto_cache' => false]);
$db_codes = $db->store('bonus_codes'); // path and options are preserved.
$db_something1 = $db->store('something1'); // path and options are preserved.
$db_something2 = $db->store('something2', ['auto_cache' => true]); // path is preserved, options are overridden.

$code1 = $db_codes->where('code', '=', $raw_code1)->fetch(); // get corresponding raw_code1 item.
$code2 = $db_codes->where('code', '=', $raw_code2)->fetch(); // get corresponding raw_code2 item.
$codes_all = $db_codes->fetch(); // get all items in db.
```

Help please.

**Comment by Kulltero** [comment]
i just came across this bug/issue aswell. hoping that this was allready addressed.

but after realizing that it wasnt i simply decided to dig arround a bit inside the code.
i realized that the conditions allways get added into a new sub-array of the conditions array, so i simply deleted the conditions array after every fetch, update, insert or delete (not using insertMany so didnt bother to change it). i had simply made this change to the src/SleekDB.php file, but ended up having to make a few different changes for it to work.

the main line to add is: 
`$this->conditions = [] `
as this resets the conditions array to no conditions applied.

simply add this on all of the insert, fetch, update and delete function just before the 'return' keyword´.
though something to note is that the fetch function returns the result of a function directly, meaning that adding the line above before the function is called will result in your query executing without any conditions. to avoid this i simply reformated it like this:

so line 43 changes from:
```PHP

return  $this->reGenerateCache();  // Returns data without looking for cached data.
```
to this:
```PHP
$TempResult = $this->reGenerateCache(); //save the result before reseting conditions
$this->conditions = []; //reset conditions array to initial state
return  $TempResult; // Returns data without looking for cached data.
```

this worked perfectly for my usecase. however i havent been messing with SleekDB for long so i'm not sure if this hardcoded fix is the best way to do it. maybe there is a usecase where you want to save conditions between calls? this was simply my 5 minute aproach to solving it!

**Comment by rakibtg** [comment]
@dima-stefantsov and @Kulltero Many thanks for the details :)
@Kulltero Instead of setting `$this->conditions = []` i think we should use `$this->initVariables()`

Tomorrow i think i will do a new release. In the meantime if you want to contribute please feel free to send a PR. 

🍻

**Comment by rakibtg** [comment]
@dima-stefantsov If you need a quick fix then please replace `fetch()` method from `SleekDB.php` as this:
```php
    // Read store objects.
    public function fetch() {
      $tmpData = null;
      // Check if data should be provided from the cache.
      if ( $this->makeCache === true ) {
        $tmpData = $this->reGenerateCache(); // Re-generate cache.
      }
      else if ( $this->useCache === true ) {
        $tmpData = $this->useExistingCache(); // Use existing cache else re-generate.
      }
      else {
        $tmpData = $this->findStoreDocuments(); // Returns data without looking for cached data.
      }
      $this->initVariables();
      return $tmpData;
    }
```

**Comment by rakibtg** [comment]
Hi @Kulltero, @dima-stefantsov  
I just did a new release [version 1.0.3](https://github.com/rakibtg/SleekDB/releases/tag/1.0.3). 
Please update to version `1.0.3` and this bug should be fixed now.
The instance state will be reset on `fetch()`, `update()`, and `delete()` method from now.
Please let me know if it works for you or if you are facing any other issues :)

**Comment by dima-stefantsov** [comment]
> @dima-stefantsov If you need a quick fix then please replace fetch() method from SleekDB.php as this:

I've considered this solution, but my deployment process does not support editing of vendor files.
I just did
```
// Instance gets dirty after each ->where() call, have to get clean instance every time.
function db_codes() {
    return \SleekDB\SleekDB::store('bonus_codes', PATH_DB, ['auto_cache' => false]);
}
...
db_codes()->where('_id', '=', $code['_id'])->update($code);
```

Btw having to write `->where('_id', '=', $code['_id'])` to update just single item looks super weird. I haven't found a proper way to save changes made to fetched items.

**Comment by rakibtg** [comment]
@dima-stefantsov Did you upgrade sleekdb to `1.0.3`?
> Btw having to write ->where('_id', '=', $code['_id']) to update just single item looks super weird. I haven't found a proper way to save changes made to fetched items.
So do you think the `update` method should return the new updated document?
