### ISSUE TITLE
A method to directly read the document by it's _id

### ISSUE THREAD

**Issue by rakibtg** [rakibtg/SleekDB#50]
Right now to find a document by it's `_id` the system will go through all the checks it has to fetch data from documents. 
As the file name of a document is identical to its `_id` and as this id will be auto generated by the system so I think it's safe and efficient to have a method `findById` which will directly read a json file of that store and return the data instead of going through all the steps.

**Comment by Timu57** [comment]
Sounds awesome!

**Comment by Timu57** [comment]
Will be done with #75
