### ISSUE TITLE
update return value

### ISSUE THREAD

**Issue by BLLuis** [rakibtg/SleekDB#51]
The update function returns true even when the underlying file_put_contents return false due to security permissions.
So, nothing where updated in the register but update returns true, see PHP log Warning:

[Sat Nov 21 01:24:51.072446 2020] [php7:warn] [pid 1870] [client 111.111.111.111:1234] PHP Warning:  file_put_contents(/home/user/data//278.json): failed to open stream: Permission denied in /php/utils/SleekDB/SleekDB.php on line 100

Maybe, update should return FALSE in such case.

Thanks.

**Comment by rakibtg** [comment]
@BLLuis What version you are using?

**Comment by Timu57** [comment]
The issue is here:

https://github.com/rakibtg/SleekDB/blob/9f4c2d95fcb7871955c066dc455a52165d2099dd/src/SleekDB.php#L205

We could fix this bug by using it like this:

```php
if(file_put_contents( $storePath, json_encode( $data ), LOCK_EX ) === false){
  throw new IOException("Unable to update file! Location: $storePath");
}
```

**Comment by rakibtg** [comment]
@Timu57 In `dev` brach there is a new method called `verifyStore`.

https://github.com/rakibtg/SleekDB/blob/ff611879249ac633faafa634cc9268bc4987ff71/src/SleekDB.php#L176-L177

I think it should handle this situation. Need to reproduce it to verify.

**Comment by rakibtg** [comment]
@BLLuis, @Timu57 Merged to dev :)

**Comment by BLLuis** [comment]
This happens to me because I run some scripts from admin (sudo) then the new registers become owned by root, so, the access to registers was ok in general but some of them because the root owner.

BTW, you should consider, in a future, to add a general flag, like the cache flag, but for a readonly file system, I mean, if readonly=true flag is provided, you should not throw the initial exception about non writable registers, then any fetch or read operation should go as normal, and in any delete or update, throw an exception, I think the deletes and updates will trow the exception as is. It will be useful in my case because I have to run with sudo just because of this. In case of readonly operations, my script will not need sudo and will read any register without throw the exception. This could be another issue(enhancement) if you like.

**Comment by BLLuis** [comment]
> @BLLuis What version you are using?

Master

**Comment by Timu57** [comment]
@BLLuis 
If you want to recommend a new feature (readonly flag) please consider making a new issue.

PS: If you want the recently made updates without waiting for the next release you can use the following command to use the dev-master branch:
```bash
composer require rakibtg/sleekdb dev-master
```

**Comment by rakibtg** [comment]
Added in [SleekDB 2.0](https://github.com/rakibtg/SleekDB/releases/tag/2.0)!
