### ISSUE TITLE
Check if data exists

### ISSUE THREAD

**Issue by rakibtg** [rakibtg/SleekDB#54]
Adding an object that can be used to determine if data exists or not! 

Example:
```php
  SleekDB::store($store, $directory)
      ->where("email", "=", "foo@bar.com")
      ->exists()
      ->fetch();
```

This will return a `true` or `false` based on the existence of the data that you are looking for.

One of the benefit of using `exists()` method will be that it can skip extra document checks when all you need to know if a document with some conditions exists or not.
It will also ignore the join operations(if any) of the query.

### 📢 Join our Telegram channel here: https://t.me/joinchat/LDAP_B1pyu3iZazrBl37Ow

**Comment by Timu57** [comment]
With #68 the exists() method returns the result.

**Comment by rakibtg** [comment]
@Timu57 Should it return a boolean response instead since we have `first` method?

**Comment by Timu57** [comment]
Yes 😊 I meant that it returns boolean instead of a SleekDB object.

**Comment by rakibtg** [comment]
Added in [SleekDB 2.0](https://github.com/rakibtg/SleekDB/releases/tag/2.0)!
