### ISSUE TITLE
Return the first item only

### ISSUE THREAD

**Issue by rakibtg** [rakibtg/SleekDB#56]
The `fetch()` method would return an array of documents. By using the `first()` method in the query we can get only the first item found, skipping additional document checks. Instead of returning an array of document it will return only a single document object.

Example:
```php
SleekDB::store($store, $dataDirectory)->first()->fetch();
```

This would return only the data object instead of a single item within an array!
```php
// Output
[
  "name" => "Foo",
  "email" => "foo@bar.com"
]
```

**Comment by Timu57** [comment]
With the implemented approach the search is efficient but for example orderBy does not work. We should mention it in the documentation.

**Comment by Timu57** [comment]
P.S. With #68 the first() method returns the result.

**Comment by rakibtg** [comment]
Added in [SleekDB 2.0](https://github.com/rakibtg/SleekDB/releases/tag/2.0)!
