### ISSUE TITLE
Cache Date in return 

### ISSUE THREAD

**Issue by stickypages** [rakibtg/SleekDB#58]
It would be awesome to have in the STORE data, to show the cache date if it's returning cached data.

**Comment by rakibtg** [comment]
@stickypages We can use something like `filemtime`.

> filemtime — Gets file modification time

Can I know about your use case?

**Comment by stickypages** [comment]
Yeah but I don't know which file it is... More so to display a date that says, "last updated". Does that help?

**Comment by rakibtg** [comment]
@stickypages I think you can add a custom property in your document like "updatedAt" and update the datetime manually. The cache files are not predictable and you will not get a proper datetime on the purpose of showing "last updated".

**Comment by stickypages** [comment]
Yeah but I don't know which file to require est to get the datetime

**Comment by Timu57** [comment]
I think you are searching for something like this? #47

**Comment by stickypages** [comment]
No, just want to know the date when the cache was last updated. Basically the file timestamp but I can't call on the file because I don't know which file to check, there are tons of files.

**Comment by Timu57** [comment]
Ok, can you please tell us your use case? For what do you need the timestamp of cached files? We need to know that, to build/ provide a good method for you.

Thank you

**Comment by stickypages** [comment]
Yeah, like I was mentioning. it's nice to know when a cache file was updated. 
Example: Am I receiving fresh data, or cached data. I don't have a way to know. Also, it's nice to know when the latest file was updated so I can reference it.

**Comment by Timu57** [comment]
@stickypages I think I get what you are trying to achieve with the date of the cached file.

Instead of giving the date and letting the user handle the caching by its own we probably should optimize/ redo the caching system to consider updated content.

I will make a new issue for that.

**Comment by Timu57** [comment]
#62 Hope this could help you.

**Comment by rakibtg** [comment]
I will close this issue, feel free to re-open!
