### ISSUE TITLE
Use "results" property instead of returning data from methods

### ISSUE THREAD

**Issue by rakibtg** [rakibtg/SleekDB#59]
- `findStoreDocuments()`
- `reGenerateCache()`
- `useExistingCache()`
This above method should use `$this->results` property to set the data directly instead of returning the data to the `fetch()` method!

In the fetch method it will only return $this->results.

**Comment by Timu57** [comment]
>     * `findStoreDocuments()`
> 
>     * `reGenerateCache()`
> 
>     * `useExistingCache()`
>       This above method should use `$this->results` property to set the data directly instead of returning the data to the `fetch()` method!
> 
> 
> In the fetch method it will only return $this->results.

 * `reGenerateCache()`
 * `useExistingCache()`
The above methods does not exist anymore. #68 

 * `findStoreDocuments()`
I did not understand why findStoreDocuments should not just return the results. So it returns the results again with #68

**Comment by rakibtg** [comment]
Added in [SleekDB 2.0](https://github.com/rakibtg/SleekDB/releases/tag/2.0)!
