### ISSUE TITLE
Wrong namespace

### ISSUE THREAD

**Issue by dima-stefantsov** [rakibtg/SleekDB#6]
```
    public function deleteStore() {
      $it = new RecursiveDirectoryIterator( $this->storePath, RecursiveDirectoryIterator::SKIP_DOTS );
      $files = new RecursiveIteratorIterator( $it, RecursiveIteratorIterator::CHILD_FIRST );
```

```
500 Internal Server Error
Class 'SleekDB\RecursiveDirectoryIterator' not found (0)
```

Can not use deleteStore() function at all. How do you even commit code without checking? Starting to get disappointed, if it has this level of errors on the surface, it's getting obvious this code is not used at all, who knows what other bad things happen inside.

**Comment by rakibtg** [comment]
@dima-stefantsov I'm really sorry for the inconvenience; fix coming tomorrow :)

**Comment by rakibtg** [comment]
Hi @dima-stefantsov  
I just did a new release [version 1.0.3](https://github.com/rakibtg/SleekDB/releases/tag/1.0.3). 
Please update to version `1.0.3` and this bug should be fixed now.
Please let me know if it works for you or if you are facing any other issues :)
