### ISSUE TITLE
Use disableCache() with join() method if parent's cache is disabled

### ISSUE THREAD

**Issue by rakibtg** [rakibtg/SleekDB#60]

**Comment by rakibtg** [comment]
Prerequisite for this issue is: #62

**Comment by Timu57** [comment]
Easy to implement now, like with data directory here:
https://github.com/rakibtg/SleekDB/blob/6866a9499568ab8abe94c4113503e5eb0b6edec1/src/Query.php#L141

Just use the private method getCondition('useCache') and check if it is false. If it is false caching is disabled.

I have to mention that users also could do that by their own if they dont want the subquery to cache by either disabling the cache store wide (the store that will be joined with) or within the join query.

But it is your choice what you want to do :smile:

I think both approaches are equally good.
Letting the users handle it or making it standard, that the subquery does not use caching if the main query does not use it.

P.S. The user can also return the results of a already fetched query with the private join function. In this case cache disabling will not be possible.
https://github.com/rakibtg/SleekDB/blob/6866a9499568ab8abe94c4113503e5eb0b6edec1/src/Query.php#L143

**Comment by Timu57** [comment]
@rakibtg 
Are you sure we should do that?

I think if someone disables the cache in the parent and that automatically disables the cache of the subquery that could be a not expected side effect to some. The user can also disable caching of the sub query (child) if he/she wants to.

Example with SleekDB:

```php
$articleStore = SleekDB::store("articles", $dataDir);
$commentStore = SleekDB::store("comments", $dataDir);

// just cache of parent store is disabled
$articleStore->disableCache()->join(function($article) use ($commentStore){
  return $commentStore->where("articleId", "=", $article["_id"]);
}, "comments");

// just cache of child store is disabled
$articleStore->join(function($article) use ($commentStore){
  return $commentStore->disableCache()->where("articleId", "=", $article["_id"]);
}, "comments");

// cache of both stores is disabled
$articleStore->disableCache()->join(function($article) use ($commentStore){
  return $commentStore->disableCache()->where("articleId", "=", $article["_id"]);
}, "comments");

```

Example with Store:

```php
$articleStore = new Store("articles", $dataDir);
$commentStore = new Store("comments", $dataDir);

$articleQueryBuilder = $articleStore->createQueryBuilder();
$commentQueryBuilder = $commentStore->createQueryBuilder();

// just cache of parent store is disabled
$articleQueryBuilder->disableCache()->join(function($article) use ($commentQueryBuilder){
  return $commentQueryBuilder->where("articleId", "=", $article["_id"]);
}, "comments");

// just cache of child store is disabled
$articleQueryBuilder->join(function($article) use ($commentQueryBuilder){
  return $commentQueryBuilder->disableCache()->where("articleId", "=", $article["_id"]);
}, "comments");

// cache of both stores is disabled
$articleQueryBuilder->disableCache()->join(function($article) use ($commentQueryBuilder){
  return $commentQueryBuilder->disableCache()->where("articleId", "=", $article["_id"]);
}, "comments");

```

If you say this feature should be implemented anyway, just assign this issue to me and I can implement it if you want to.
