### ISSUE TITLE
Update multiple records at once

### ISSUE THREAD

**Issue by dashpilot** [rakibtg/SleekDB#7]
Is it possible to update multiple records at once? My use case is that I need to change one value in several records (in the same store) at once. I tried it in a loop, but that doesn't seem to work as expected.

**Comment by rakibtg** [comment]
@dashpilot It would be great if you can show some code :) 
Did you try multiple `where` methods? Example:
```php
$updateable = [
    'products' => [
      'totalBought' => 1
    ]
  ];
  $usersDB
    ->where( 'country', '=', 'Unknown' )
    ->where( 'age', '>=', '18' )
    ->update( $updateable );
```

**Comment by dashpilot** [comment]
Thanks for your fast reply, love SleekDB a lot!

I'm trying to give each entry a different 'order_id', for ordering entries. I tried it a few days ago, but did something like:

`
$order = [14,23,7,2]; // these are the entry id's

$i=0;
foreach($item as $val){

$data = array( 'order_id' => $i);
$postsDB
    ->where( '_id', '=', $val)
    ->update($data);

$i++;
}
`

**Comment by rakibtg** [comment]
Hi @dashpilot 
I just did a new release [version 1.0.3](https://github.com/rakibtg/SleekDB/releases/tag/1.0.3). 
Please update to version `1.0.3` and this bug should be fixed now.
Please let me know if it works for you or if you are facing any other issues :)

**Comment by dashpilot** [comment]
Hi @rakibtg 
I just tested version 1.0.3, and it works like a charm now! Thanks for the quick fix and and for making SleekDB as awesome as it is :)

**Comment by dashpilot** [comment]
I'll close the issue now, fixed.

**Comment by rakibtg** [comment]
@dashpilot Great to know that you liked it :)
