### ISSUE TITLE
Add update & delete to Store class

### ISSUE THREAD

**Issue by Timu57** [rakibtg/SleekDB#78]
For simple queries conveniently update and delete documents without the need of QueryBuilder.

Update one or multiple documents.
```php
function update($documents): bool
```

Delete one document.
```php
function deleteDocument($id, $returnOption = Query::DELETE_RETURN_RESULTS): array|bool|int
```
For more return options look into #77

**Comment by rakibtg** [comment]
@Timu57 `deleteDocument` would it be a public API or internal method?

**Comment by Timu57** [comment]
@rakibtg yes, because the Store class already has a delete method to delete a store.

I also thought about naming the method **deleteById**

What do you think what could be the best fitting name?

**Comment by rakibtg** [comment]
@Timu57 Can't we already do that? Example:

```php
$qb = $store->getQueryBuilder();

$foo = $qb->where("name", "=", "Foo")->getQuery();

print_r($foo->fetch());

$foo->update(["age" => 12]);

print_r($foo->fetch());

$foo->delete();
```

**Comment by Timu57** [comment]
@rakibtg yes we can.
But the following is much more convenient:
```php
$store->deleteById($id);
```
We also could create a `deleteBy` method:
```php
function deleteBy($criteria, $returnOption = Query::DELETE_RETURN_BOOL): bool|int|array
```
- $criteria
  - ["city" => "london", "age" => 18]
- $returnOption
  - see return options constants at #77

**Comment by rakibtg** [comment]
@Timu57 I have mixed feeling for `findBy` or `deleteBy` because 
 - it might be a query consistency issue
 - What if we add more conditional methods, or if i want to add search in the findBy method then every time we will need to add a new parameter, which i think would create more confusion
