### ISSUE TITLE
Remove insertMany and provide that functionallity with insert

### ISSUE THREAD

**Issue by Timu57** [rakibtg/SleekDB#86]
We should provide inserting multiple documents with one method. Would make using SleekDB a little bit easier.

**Comment by rakibtg** [comment]
@Timu57 I would say No, as there will be no way to judge when it actually contains multiple items or if a single document should have a list of data! So, let's keep `insertMany` besides `insert`

**Comment by Timu57** [comment]
> @Timu57 I would say No, as there will be no way to judge when it actually contains multiple items or if a single document should have a list of data! So, let's keep `insertMany` besides `insert`

@rakibtg we already do that kind of decision in the new update method of the Store class and the where and orWhere methods of the QueryBuilder class

**Comment by rakibtg** [comment]
Oh, did you mean this?
```php
$store->createQueryBuilder()->getQuery()->insert(["" => ""], ["" => ""], ["" => ""]);
```

**Comment by Timu57** [comment]
No, just the Store class has insert methods, none other method does.

For example in the update method we achieved the decision if the given array contains one or multiple documents with this line of code:

```php
$multipleDocuments = array_keys($updatable) === range(0, (count($updatable) - 1));
```

**Comment by Timu57** [comment]
@rakibtg 
I just noticed something.
Should SleekDB be able to accept the following as a document?

```php
$document = ["value1","value2","value3"]; // (Keys are: 0, 1, 2)
```

If so you are right, then we would need to provide both methods.
Otherwise we could remove the `insertMany` method and provide that functionality with the `insert` method

**Comment by rakibtg** [comment]
@Timu57 There's a corner case,

This could be a single document:

```php
$data = [
    [ "foo" => "bar" ],
    [ "fiz" => "baz" ]
];
```

Again, this could be two single document,


```php
$data = [
    [ "foo" => "bar" ],
    [ "fiz" => "baz" ]
];
```

That's why we need both `insert` and `insertMany` methods.

**Comment by Timu57** [comment]
Ok, I get it, a document does not have to be an associative array.

**Comment by rakibtg** [comment]
Most likely no one will insert an array directly, but let's keep the insertMany to avoid further confusions.

**Comment by Timu57** [comment]
yes, you are right, it's the best to keep both methods.
