### ISSUE TITLE
getCache method in Store

### ISSUE THREAD

**Issue by Timu57** [rakibtg/SleekDB#87]
Should we make a `getCache` method in the `Store` class for an easier access to the Cache object?

```php
public function getCache(){
  return $this->createQueryBuilder()->getQuery()->getCache();
}
```

The `Cache` class provides methods like: `deleteWithNoLifetime` and `deleteAll`.

We also could make a wrapper for some of these methods or just let it like it is now.

Most of the time the user does not need any access to the cache object and its methods.
That's why I would say that we can let it like it is now.

**Comment by rakibtg** [comment]
Does it make any difference of facilates #88 ?

**Comment by Timu57** [comment]
@rakibtg 
The user could have an easier direct access to the Cache object with all its methods.

But to be honest I don't think that this kind of direct access is really needed..
