### ISSUE TITLE
useCache method in Store class

### ISSUE THREAD

**Issue by Timu57** [rakibtg/SleekDB#88]
We should consider adding a `useCache` and a `disableCache` method to the `Store` class, perhaps also a `regenerateCache` method.
These methods should set a separate cache flag for the new methods to provide a manual query by query base caching like with the QueryBuilder.

The user could also just use the configuration when creating the Store object, but that would be store wide and would be a little bit inconvenient.

**Comment by rakibtg** [comment]
OH! Yes. I think it will be a very important feature otherwise it might cause a lot of foreign bugs while caching complex queries.

**Comment by Timu57** [comment]
At the time we don't have these methods in the Store class, do you think we should add them?

**Comment by rakibtg** [comment]
@Timu57 The `createQueryBuilder` will have all this methods?

**Comment by Timu57** [comment]
> @Timu57 The `createQueryBuilder` will have all this methods?

@rakibtg yes it has all these methods. The only benefit would be that the used can control the cache when using for example the `findBy` method.

**Comment by rakibtg** [comment]
If we use `createQueryBuilder` then we don't need them in the store class!
