### ISSUE TITLE
Make an OR between array elements of where method

### ISSUE THREAD

**Issue by Timu57** [rakibtg/SleekDB#90]
# Current behaviour

Currently the `where` method of the `QueryBuilder` class accepts a multidimensional array, where the different statements have an `AND` between them.

That provides an handy way to make multiple `AND` statements without calling the `where` method multiple times.

For example:

```php
$queryBuilder
  ->where(["name", "=", "John"])
  ->where(
    [
      ["city", "=", "london"],
      ["age", "=", 18]
    ]
  )
```

Will produce the following statement:
```sql
WHERE name = "John" AND ( city = "london" AND age = 18 )
```

The same kind of query can be achieved with the following code:

```php
$queryBuilder
  ->where(["name", "=", "John"])
  ->where(["age", "=", 18])
  ->where(["city", "=", "london"])
```

```sql
WHERE name = "John" AND city = "london" AND age = 18
```

# Alternative behaviour

When using `AND` there is **no need for the parentheses** and there is no possibility to make the following request, also not when using the `orWhere()` method:

```sql
WHERE name = "John" AND (city = "london" OR age = 18)
```

Thats why I think we should just make an `OR` between each element when the user provides an multidimensional array to the `where` method.

# Futher thoughts

It seems like using parentheses is just needed when there is a swap of `OR` and `AND`.
Thats why we could also provide a way to make nested requests with that approach.

```php
$queryBuilder
  ->where(["name", "=", "John"])
  ->where(
    [
      [
        ["city", "=", "london"],
        ["age", "=", 21]
      ],
      ["age", "=", 18]
    ]
  )
```

```sql
WHERE name = "John" AND ((city = "london" AND age = 21) OR age = 18)
```

That way we could provide a nested where functionality like mentioned in #80 by @adrxn with https://github.com/rakibtg/SleekDB/issues/80#issuecomment-763671096

**Comment by rakibtg** [comment]
@Timu57 I think I liked the one you talked about in our [discord](https://discord.gg/WJGqUFPtZw) channel.

**Comment by Timu57** [comment]
We will implement an additional method with the release of 2.1, that handles nested where conditions and let the where method as is.
