### ISSUE TITLE
Add a new method for nested where conditions

### ISSUE THREAD

**Issue by Timu57** [rakibtg/SleekDB#91]
As pointed out by @adrxn in https://github.com/rakibtg/SleekDB/issues/80#issuecomment-763671096 the current implementation does not support nested where clauses.

The new method should accept an array like this:

```php
[
  "and" => [
    "and" => [
      [
        "or" => [
          [ "name", "like", "a%" ],
          [ "name", "like", "b%" ]
        ]
      ],
      [
        "or" => [
          [
            "and" => [
              [ "age", ">=", 16 ],
              [ "age", "<", 20 ]
            ]
          ],
          [
            "and" => [
              [ "age", ">=", 24 ],
              [ "age", "<", 28 ]
            ]
          ]
        ]
      ]
    ]
  ]
];
```

To provide the following request:
```sql
WHERE ( (name like 'a%' OR name like 'b%') AND ((age >= 16 AND age < 20) or (age >= 24 AND age < 28)) )
```

# Array structure / Concept

```php
"OUTERMOST_OPERATION" => [
  "OPERATION_DEPTH_1" => [
    [
      "OPERATION_DEPTH_2" => [
        ["CLAUSE"],
        "OPERATION_DEPTH_3" => [
          ["CLAUSE"],
          ["CLAUSE"]
        ]
      ]
    ]
]
```

## OUTERMOST_OPERATION
The outermost operation is optional and does specify how the given conditions are connected with other conditions, like the ones that are specified using the `where`, `orWhere`, `in` or `notIn` methods. If this operation is not given it will default to an `AND` operation.

Because the outermost operation represents the connection of the given conditions towards the "outer world" it has to have one child element that specifies the `OPERATION_DEPTH_1`.

Meaning the following array will not be allowed and will throw an error:

```php
"or" => [
  [ "name", "like", "a%" ]
];
```

## OPERATION_DEPTH_X
To specify a nested condition these operations are mandatory. They also have to have at least two children to be of any use. The children-amount >= 2 should not be enforced by SleekDB. 

If you have for example the following array as a "conditions array" it should work without errors. Unfortunately it will not bring much additional functionality because it can also be done with a simple `orWhere` call:

```php
"or" => [
  "and" => [
    [ "name", "like", "a%" ],
  ]
];
```

```sql
WHERE ( name like "a%" ) OR ...
```

**Comment by rakibtg** [comment]
Are we going to call it `condition()` method?

**Comment by Timu57** [comment]
The implementation of the nested where functionality like shown in https://github.com/rakibtg/SleekDB/issues/91#issue-792616517 is very difficult.
While trying to implement it I also noticed that the approach was very difficult and unintuitive to use.

With the new implementation everything is much simpler and cleaner.

```sql
WHERE ( (name like 'a%' OR name like 'b%') AND ((age >= 16 AND age < 20) or (age >= 24 AND age < 28)) )
```

```php
[
  "and" => [
    [
      [ "name", "like", "a%" ], "or", [ "name", "like", "b%" ]
    ],
    "and",
    [
      [
        [ "age", ">=", 16 ], "and", [ "age", "<", 20 ]
      ],
      "or",
      [
        [ "age", ">=", 24 ], "and", [ "age", "<", 28 ]
      ]
    ]
  ]
];
```

# Array structure / Concept

```php
[
  "OUTERMOST_OPERATION" => [
    // conditions
  ]
];
```

# OUTERMOST_OPERATION
The outermost operation is optional and does specify how the given conditions are connected with other conditions, like the ones that are specified using the `where`, `orWhere`, `in` or `notIn` methods. If this operation is not given it will default to an `AND` operation.

**Comment by Timu57** [comment]
Implemented with version 2.2

**Comment by adrxn** [comment]
Sorry for the late replay ...
I agree that your syntax is closer to the normal infix notations and thus more intuitive.
I was thinking more in function (prefix) notation.

Maybe now you do not need the OUTERMOST_CONDITION at all.

May I suggest defining more comparison operators like:

function Compare($field, $compare, $value) {

    $ok = false;

    switch (strtolower($compare)) {
        case "=":
        case "==":
        case "===":
            $ok =  $field === $value;
            break;
        case "!=":
        case "!==":
        case "<>":
            $ok =  $field !== $value;
            break;
        case "<":
            $ok =  $field < $value;
            break;
        case "<=":
            $ok =  $field <= $value;
            break;
        case ">":
            $ok =  $field > $value;
            break;
        case ">=":
            $ok =  $field >= $value;
            break;
        case "contains":
            $ok =  str_contains($field, $value);
            break;
        case "in":
            $ok =  str_contains($value, $field);
            break;
        case "like":
            $ok =  fnmatch($value, $field);
            break;
        case "notlike":
            $ok =  !fnmatch($value, $field);
            break;
        case "match":
            preg_match($value, $field, $matches);
            $ok = (count($matches) > 0);
            break;
        case "notmatch":
            preg_match($value, $field, $matches);
            $ok = (count($matches) <= 0);
            break;
    }

    return $ok;
}

**Comment by Timu57** [comment]
Hi @adrxn Could you please open a new issue for your enhancement request. Thank you

**Comment by Timu57** [comment]
> Sorry for the late replay ...
> I agree that your syntax is closer to the normal infix notations and thus more intuitive.
> I was thinking more in function (prefix) notation.
> 
> Maybe now you do not need the OUTERMOST_CONDITION at all.

@adrxn Thank you for your thinking and suggestion. I am sorry but I don't quiet understand what you meant, how we can change it, that we don't need the outermost condition any more. Could you please explain it in more detail? :sweat_smile:
Thank you in advance.

### Quick summary what the outermost condition is for

When the user defines conditions to filter data with for example the where and orWhere methods, the outermost condition is used to decide if the conditions defined with nestedWhere have to be checked (AND operation) or not (OR operation).
