### ISSUE TITLE
Uncaught SleekDB\Exceptions\InvalidConfigurationException: cache_lifetime has to be null or int

### ISSUE THREAD

**Issue by REDAL** [rakibtg/SleekDB#92]
![test](https://user-images.githubusercontent.com/7544360/105754459-60222080-5f4a-11eb-899c-8071833c9276.png)

I got this message when trying to add configuration parameters

this is the code that caused the issue

require_once __DIR__.'/plugins/SleekDB/Store.php';
    
    $dbDir = $_SERVER['DOCUMENT_ROOT']."/db/";
    $configuration = [
    "auto_cache" => true,
    "cache_lifetime" => null,
    "timeout" => 120
  ];    
    $newsStore = new \SleekDB\Store("news", $dbDir, $configuration);

**Comment by Timu57** [comment]
@REDAL Hi and thank you for reporting the bug. An update containing the fix will be released very soon.

**Comment by REDAL** [comment]
the message error is disappeared, but no cache file is generated in the cache folder

**Comment by rakibtg** [comment]
@REDAL What happens when you have no `cache_lifetime` in the configuration?

**Comment by REDAL** [comment]
Actually, nothing happens, when removing cache_lifetime from the configuration, I mean no error occurs, it does save the data.

**Comment by Timu57** [comment]
> the message error is disappeared, but no cache file is generated in the cache folder

SleekDB does create Cache files when executing a search query.
Does SleekDB create a cache file when you use the following code?

```php
$store->findAll();
```

Then there should be a cache file located in:

```php
$dbDir . "<YOUR_STORE_NAME>" . "/cache"
```

PS: Hope we can release v2.0.1 today, that includes the fix.

**Comment by Timu57** [comment]
Version 2.0.1 is released and should fix this bug.
@REDAL thank you for reporting the bug.
If the bug is still not fixed, feel free to reopen this issue.

**Comment by rakibtg** [comment]
Thanks @Timu57 for the quick fix and release.
