### ISSUE TITLE
bloGo a noSQL Blog, thanks @SleekDB

### ISSUE THREAD

**Issue by gusgeek** [rakibtg/SleekDB#93]
This enchanted with your project, is really of exceptional utility and with an amazing way of working. I decided to get down to business and try your library, to see as soon as I was humming myself to create a Blog from its implementation to the way it handled the data. Literally late 4 days., I don't know if because of my speed or because it wasn't a headache worrying about the characteristics of the database and its behavior, but I was amazed at the ease of implementation and the power it has. I decided to bring it to you for you to see, I uploaded it to a Git and it's for the audience. Naming your project as suposed.

[gusgeek/blogo](https://github.com/gusgeek/bloGo)

**Comment by Timu57** [comment]
@gusgeek Hi and thank you for your kind words. It's beautiful to hear such a positive feedback and we are glad that you like SleekDB. Your blog software looks good and I hope you will be able to build awesome things with SleekDB.
