### ISSUE TITLE
Undefined index: order

### ISSUE THREAD

**Issue by netomarchiori** [rakibtg/SleekDB#99]
Hello there,

I keep getting "Undefined index: order" on Query.php line 510, even when using methods that does not require me to provide order parameters, such as findAll():

`$allNews = $newsStore->findAll();`

Running PHP 7.4.14 and using SleekDB with Laravel 8

**Comment by Timu57** [comment]
Hi @netomarchiori
I also noticed that bug today and its fixed with version 2.1.1

Feel free to reopen this issue if the bug still occurs after updating to v2.1.1
